export interface MarketingTier {
  name: string
  nameAr: string
  taglineEn: string
  taglineAr: string
  builtForEn: string
  builtForAr: string
  deliverablesEn: { category: string, items: string[] }[]
  deliverablesAr: { category: string, items: string[] }[]
  notIncludedEn?: string
  notIncludedAr?: string
}

export interface MarketingService {
  slug: string
  titleEn: string
  titleAr: string
  descEn: string
  descAr: string
  metaTitleEn: string
  metaTitleAr: string
  metaDescEn: string
  metaDescAr: string
  heroEn: string
  heroAr: string
  whyHeadingEn: string
  whyHeadingAr: string
  whyEn: string
  whyAr: string
  deliverablesHeadingEn: string
  deliverablesHeadingAr: string
  deliverablesEn: string[]
  deliverablesAr: string[]
  processStepsEn: { label: string; text: string }[]
  processStepsAr: { label: string; text: string }[]
  industriesHeadingEn: string
  industriesHeadingAr: string
  industriesEn: string
  industriesAr: string
  whyPremieraHeadingEn: string
  whyPremieraHeadingAr: string
  whyPremieraEn: string
  whyPremieraAr: string
  complianceHeadingEn: string
  complianceHeadingAr: string
  complianceEn: string
  complianceAr: string
  faqsEn: { q: string; a: string }[]
  faqsAr: { q: string; a: string }[]
  relatedSlugs: string[]
  ctaEn: string
  ctaAr: string
  // packages page fields
  isPackages?: true
  packagesHeroEn?: string
  packagesHeroAr?: string
  packagesTiers?: MarketingTier[]
  websiteDevEn?: string
  websiteDevAr?: string
  websiteDevItemsEn?: { heading?: string; paragraph?: string; subHeading?: string; items?: string[]; subItems?: string[] }[]
  websiteDevItemsAr?: { heading?: string; paragraph?: string; subHeading?: string; items?: string[]; subItems?: string[] }[]
  websiteCareEn?: string
  websiteCareAr?: string
  websiteCareItemsEn?: { heading?: string; paragraph?: string; subHeading?: string; items?: string[]; subItems?: string[] }[]
  websiteCareItemsAr?: { heading?: string; paragraph?: string; subHeading?: string; items?: string[]; subItems?: string[] }[]
  scaleBenefitsEn?: string[]
  scaleBenefitsAr?: string[]
  packagesFaqsEn?: { q: string; a: string }[]
  packagesFaqsAr?: { q: string; a: string }[]
}

const SERVICES: MarketingService[] = [
  {
    slug: 'social-media-management-saudi',
    titleEn: 'Social Media Management in Saudi Arabia',
    titleAr: 'إدارة وسائل التواصل الاجتماعي في السعودية',
    descEn: 'We manage social media for Saudi businesses — Arabic-first content, daily publishing, community management, and monthly reporting.',
    descAr: 'ندير حسابات التواصل الاجتماعي للشركات السعودية — محتوى عربي أصيل، ونشر منتظم، وإدارة تفاعل، وتقارير شهرية.',
    metaTitleEn: 'Social Media Management in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إدارة وسائل التواصل الاجتماعي في السعودية | بريميرا لايف',
    metaDescEn: 'We manage social media for Saudi businesses — Arabic-first content, daily publishing, community management, and monthly reporting.',
    metaDescAr: 'ندير حسابات التواصل الاجتماعي للشركات السعودية — محتوى عربي أصيل، ونشر منتظم، وإدارة تفاعل، وتقارير شهرية. اتصل بنا للنقاش.',
    heroEn: 'Most Saudi businesses do not have a social media problem. They have a consistency problem. Posting stops when the person who was posting gets busy, the feed goes quiet for three weeks, and the audience they spent months building forgets they exist. We run your social media as a monthly operation — planned in advance, published on schedule, answered every day, and reported at the end of every month.',
    heroAr: 'لا تعاني معظم الشركات السعودية من مشكلة في وسائل التواصل الاجتماعي، بل من مشكلة في الاستمرارية. يتوقف النشر حين ينشغل الموظف المسؤول، فيصمت الحساب ثلاثة أسابيع، وينسى الجمهور الذي بنيته خلال أشهر أنك موجود. ندير حساباتك كعملية شهرية منظمة: نخطط مسبقًا، وننشر في مواعيدها، ونرد يوميًا، ونقدّم تقريرًا في نهاية كل شهر.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: 'Your customers in Saudi Arabia are not browsing one platform. They are on Snapchat in the morning, TikTok at night, Instagram when they are shopping, and X when they are complaining. Each of those platforms has a different job, a different content format, and a different audience for your business.\n\nHanding all of it to one junior employee with a phone is how brands end up posting the same landscape graphic to four platforms and wondering why nothing happens. Handing it to an agency that translates English captions into stiff Modern Standard Arabic is how brands end up sounding like a government circular.\n\nWe plan each platform for what it actually does, produce content built for that format, and write in the language your audience uses.',
    whyAr: 'لا يتابع عملاؤك في السعودية منصة واحدة. يفتحون سناب شات صباحًا، وتيك توك ليلًا، وإنستغرام حين يتسوقون، وX حين يشتكون. ولكل منصة دور مختلف، وصيغة مختلفة، وجمهور مختلف لعملك.\n\nوحين تُسلّم هذا كله لموظف واحد بهاتفه، تنتهي بنشر التصميم نفسه على أربع منصات وتتساءل لماذا لا يحدث شيء. وحين تُسلّمه لشركة تترجم التعليقات من الإنجليزية إلى عربية جامدة، تنتهي بعلامة تبدو كتعميم إداري.\n\nنخطط كل منصة وفق دورها الحقيقي، وننتج محتوى مبنيًا لصيغتها، ونكتب باللغة التي يستخدمها جمهورك فعلًا.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Monthly content calendar — planned and approved by you before anything goes live. You always know what is publishing and when.',
      'Arabic-first copywriting — written in Arabic, not translated into it. English versions where your audience is bilingual.',
      'Platform-native content — vertical video for Snapchat and TikTok, carousels and reels for Instagram, short text for X. No landscape video squeezed into a vertical frame.',
      'Publishing and scheduling — posted at the times your audience is actually awake and free, planned around prayer times and the Friday–Saturday weekend.',
      'Community management — comments and DMs answered in Arabic and English, with a response protocol you approve for pricing questions, complaints, and press.',
      'Seasonal campaign planning — Ramadan, Eid, Saudi National Day, Founding Day, and your own commercial calendar, planned months out instead of scrambled together the week before.',
      'Monthly report — reach, engagement, follower growth, top-performing content, and what we are changing next month.',
    ],
    deliverablesAr: [
      'خطة محتوى شهرية — نخططها وتوافق عليها قبل نشر أي شيء. تعرف دائمًا ما سيُنشر ومتى.',
      'كتابة عربية أصيلة — نكتب بالعربية، ولا نترجم إليها. ونكتب نسخًا إنجليزية حين يكون جمهورك ثنائي اللغة.',
      'محتوى مصمم لكل منصة — فيديو عمودي لسناب شات وتيك توك، وكاروسيل وريلز لإنستغرام، ونصوص قصيرة لـX. لا نضغط فيديو أفقيًا داخل إطار عمودي.',
      'النشر والجدولة — ننشر في الأوقات التي يكون فيها جمهورك متفرغًا، ونخطط حول أوقات الصلاة وعطلة الجمعة والسبت.',
      'إدارة التفاعل — نرد على التعليقات والرسائل بالعربية والإنجليزية، وفق بروتوكول رد توافق عليه للأسعار والشكاوى والإعلام.',
      'تخطيط المواسم — نخطط لرمضان والعيد واليوم الوطني ويوم التأسيس وروزنامتك التجارية قبل أشهر، لا في الأسبوع السابق.',
      'تقرير شهري — الوصول والتفاعل ونمو المتابعين وأفضل المحتوى أداءً، وما سنغيّره الشهر القادم.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'we map your goals, your audience, and which platforms actually deserve your budget. Some businesses should not be on four platforms. We will tell you that.' },
      { label: 'Monthly plan', text: 'you receive the content calendar for the coming month and approve it before production starts.' },
      { label: 'Production', text: 'content shot, designed, and written. See our content production service for how that runs.' },
      { label: 'Publish and manage', text: 'everything goes out on schedule; comments and messages are handled daily.' },
      { label: 'Report and adjust', text: "you get the numbers at the end of the month, and next month's plan reflects what they told us." },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'نحدد أهدافك وجمهورك والمنصات التي تستحق ميزانيتك فعلًا. لا يجب أن تكون بعض الأعمال على أربع منصات، وسنقول لك ذلك.' },
      { label: 'خطة شهرية', text: 'تستلم خطة المحتوى للشهر القادم وتوافق عليها قبل بدء الإنتاج.' },
      { label: 'الإنتاج', text: 'نصوّر ونصمم ونكتب. راجع خدمة إنتاج المحتوى لتفاصيل ذلك.' },
      { label: 'النشر والإدارة', text: 'ينشر كل شيء في موعده، ونتابع التعليقات والرسائل يوميًا.' },
      { label: 'التقرير والتعديل', text: 'تستلم الأرقام في نهاية الشهر، وتعكس خطة الشهر التالي ما قالته.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Restaurants and cafés · Hotels and hospitality · Healthcare and clinics · Retail and e-commerce · Real estate and developers · Automotive · Education · Industrial and manufacturing · Government and semi-government entities',
    industriesAr: 'المطاعم والمقاهي · الفنادق والضيافة · الرعاية الصحية والعيادات · التجزئة والمتاجر الإلكترونية · العقار والمطوّرون · السيارات · التعليم · الصناعة والتصنيع · الجهات الحكومية وشبه الحكومية',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: 'We are not a social media agency that outsources the filming. We are a film and software company that also runs social media, which means the content on your feed is produced by the same crew that shoots commercial films for global brands — 15+ years, 1,000+ projects, 20+ global brands.\n\nThat matters practically. When you need a video by Thursday, we do not brief a freelancer and hope. We shoot it.',
    whyPremieraAr: 'لسنا وكالة تواصل اجتماعي تُسند التصوير إلى غيرها. نحن شركة أفلام وبرمجيات تدير أيضًا وسائل التواصل، ما يعني أن المحتوى على حسابك ينتجه الفريق نفسه الذي يصوّر أفلامًا تجارية لعلامات عالمية — أكثر من 15 عامًا، وأكثر من 1,000 مشروع، وأكثر من 20 علامة عالمية.\n\nولهذا أثر عملي: حين تحتاج فيديو يوم الخميس، لا نرسل بريفًا لمصوّر مستقل ونتمنى. نصوّره بأنفسنا.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'Every piece of content is produced to Saudi advertising standards: modest dress, no wealth flaunting, no children in promotional content, no claims we cannot support. Paid promotions are labelled as advertising. When a campaign calls for creators, we work only through Mawthooq-licensed influencers.\n\nMarketing that grows your brand — and protects it.',
    complianceAr: 'ننتج كل محتوى وفق معايير الإعلان في المملكة: لباس محتشم، وبلا استعراض للثراء، وبلا أطفال في المحتوى الترويجي، وبلا ادعاءات لا نستطيع إثباتها. نوسم المحتوى المدفوع بوصفه إعلانًا. وحين تتطلب الحملة صنّاع محتوى، نعمل حصريًا عبر مرخّصين في منصة موثوق.\n\nنقدّم تسويقًا ينمّي علامتك — ويحميها.',
    faqsEn: [
      { q: 'Which platforms should my business be on in Saudi Arabia?', a: 'It depends entirely on who buys from you. A clinic in Riyadh and an industrial supplier in Jubail should not have the same platform mix. We answer this specifically in the strategy session rather than putting you on everything by default.' },
      { q: 'Do you write in Arabic, or translate from English?', a: 'We write in Arabic. Translated Arabic reads as translated Arabic, and Saudi audiences notice immediately. Where your audience is bilingual, we write both versions natively.' },
      { q: 'How often will you post?', a: 'That is set in your monthly plan and depends on your retainer scope and platform mix. We would rather post three strong pieces a week than seven weak ones.' },
      { q: 'Who owns the accounts and the content?', a: 'You do. Always. Accounts stay in your name with your admin access, and every asset we produce is yours. If we ever stop working together, nothing walks out the door with us.' },
      { q: 'Do you handle comments and direct messages?', a: 'Yes, within your agreed scope. We build a response protocol with you covering pricing questions, complaints, and anything that needs to escalate to you before we reply.' },
      { q: 'Can you work alongside our in-house marketing team?', a: 'Yes. Some clients want everything run for them; others want us handling production and strategy while their team publishes. Both work.' },
      { q: 'Do you work with influencers?', a: 'Yes, through Mawthooq-licensed creators only. Unlicensed influencer advertising is a regulatory exposure we will not put a client into.' },
      { q: 'How long before we see results?', a: 'Community growth and engagement usually move within the first two to three months of consistent publishing. Anyone who promises you a specific number by a specific date is guessing.' },
      { q: 'Do you only work in Riyadh?', a: 'We work across the Kingdom — Riyadh, Jeddah, Khobar, Dammam, Jubail, and the Eastern Province — and we travel for production.' },
    ],
    faqsAr: [
      { q: 'ما المنصات التي يجب أن يكون عملي عليها في السعودية؟', a: 'يعتمد ذلك كليًا على من يشتري منك. لا ينبغي أن تتشابه عيادة في الرياض ومورّد صناعي في الجبيل في مزيج المنصات. نجيب عن هذا تحديدًا في الجلسة الاستراتيجية بدل وضعك على كل شيء افتراضيًا.' },
      { q: 'هل تكتبون بالعربية أم تترجمون من الإنجليزية؟', a: 'نكتب بالعربية. تُقرأ العربية المترجمة كعربية مترجمة، ويلاحظ الجمهور السعودي ذلك فورًا. وحين يكون جمهورك ثنائي اللغة، نكتب النسختين أصالةً.' },
      { q: 'كم مرة ستنشرون؟', a: 'نحدد ذلك في خطتك الشهرية، ويعتمد على نطاق اشتراكك ومزيج منصاتك. نفضّل ثلاثة منشورات قوية أسبوعيًا على سبعة ضعيفة.' },
      { q: 'من يملك الحسابات والمحتوى؟', a: 'تملكها أنت، دائمًا. تبقى الحسابات باسمك وبصلاحياتك، وكل أصل ننتجه ملك لك. وإن توقف تعاوننا يومًا، لا يخرج شيء معنا.' },
      { q: 'هل تديرون التعليقات والرسائل الخاصة؟', a: 'نعم، ضمن النطاق المتفق عليه. نبني معك بروتوكول رد يغطي أسئلة الأسعار والشكاوى وكل ما يستدعي الرجوع إليك قبل الرد.' },
      { q: 'هل يمكنكم العمل مع فريقنا الداخلي؟', a: 'نعم. يريد بعض العملاء إدارة كل شيء، ويريدنا آخرون في الاستراتيجية والإنتاج بينما ينشر فريقهم. كلاهما يعمل.' },
      { q: 'هل تتعاونون مع المؤثرين؟', a: 'نعم، عبر صنّاع محتوى مرخّصين في منصة موثوق حصريًا. لا نضع عميلًا في مخاطرة تنظيمية بإعلانات مؤثرين غير مرخّصين.' },
      { q: 'متى نرى النتائج؟', a: 'يتحرك نمو المجتمع والتفاعل عادة خلال أول شهرين إلى ثلاثة من النشر المستمر. ومن يعدك برقم محدد في تاريخ محدد يخمّن.' },
      { q: 'هل تعملون في الرياض فقط؟', a: 'نعمل في أنحاء المملكة — الرياض وجدة والخبر والدمام والجبيل والمنطقة الشرقية — ونسافر للإنتاج.' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'seo-saudi', 'content-production-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'google-ads-saudi',
    titleEn: 'Google Ads Management in Saudi Arabia',
    titleAr: 'إدارة إعلانات Google في السعودية',
    descEn: 'Google Ads managed for Saudi businesses — Arabic and English campaigns, conversion tracking, and full accountability for every riyal of ad spend.',
    descAr: 'ندير حملات Google للشركات السعودية — حملات عربية وإنجليزية، وتتبع تحويلات دقيق، ومساءلة كاملة عن كل ريال إعلاني.',
    metaTitleEn: 'Google Ads Management in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إدارة إعلانات Google في السعودية | بريميرا لايف',
    metaDescEn: 'Google Ads managed for Saudi businesses — Arabic and English campaigns, conversion tracking, and full accountability for every riyal of ad spend.',
    metaDescAr: 'ندير حملات Google للشركات السعودية — حملات عربية وإنجليزية، وتتبع تحويلات دقيق، ومساءلة كاملة عن كل ريال إعلاني.',
    heroEn: 'Google Ads is the only channel where people tell you exactly what they want, in their own words, at the moment they want it. It is also the easiest channel to waste money on. We manage Saudi Google Ads accounts with full accountability for every riyal of spend — what it bought, what it returned, and what we are changing because of it.',
    heroAr: 'تُعد إعلانات Google القناة الوحيدة التي يخبرك فيها الناس بما يريدونه تمامًا، بكلماتهم، في اللحظة التي يريدون فيها. وهي أيضًا أسهل قناة لإهدار المال عليها. ندير حسابات Google السعودية بمساءلة كاملة عن كل ريال: ماذا اشترى، وماذا أعاد، وما الذي نغيّره بناءً عليه.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: 'Someone searching "أفضل عيادة أسنان في الرياض" is not browsing. They have a problem and a wallet open. Whether they land on you or your competitor is decided by keyword strategy, ad relevance, landing page quality, and bid management — four things that most Saudi accounts get wrong in the same predictable ways.\n\nThe most common: running English-only campaigns in a country that searches in Arabic. The second most common: sending expensive clicks to a slow homepage instead of a page built to convert.',
    whyAr: 'من يبحث عن «أفضل عيادة أسنان في الرياض» لا يتصفح. لديه مشكلة ومحفظة مفتوحة. ويتحدد وصوله إليك أو إلى منافسك عبر أربعة أمور: استراتيجية الكلمات، وصلة الإعلان، وجودة صفحة الهبوط، وإدارة المزايدة — وتُخطئ معظم الحسابات السعودية فيها بالطريقة المتوقعة نفسها.\n\nأشيع خطأ: تشغيل حملات بالإنجليزية فقط في بلد يبحث بالعربية. وثانيها: إرسال نقرات مكلفة إلى صفحة رئيسية بطيئة بدل صفحة مبنية للتحويل.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Bilingual keyword research — Arabic and English. Arabic search is not a translation of English search. People use dialect, transliteration, and shorthand that no English keyword list will surface.',
      'Campaign build — Search, Performance Max, YouTube, Display, and remarketing, chosen for your business rather than switched on by default.',
      'Ad copy in both languages — written natively, tested continuously.',
      'Conversion tracking that actually works — GA4, conversion actions, call tracking, and WhatsApp click tracking. Saudi buyers convert on WhatsApp far more than on forms, and an account that only counts form fills is lying to you about its own performance.',
      'Landing page strategy — we build the pages too. If your landing page is the bottleneck, we can fix it instead of writing it up in a report.',
      'Negative keyword management — ongoing, because half of Google Ads is deciding what you refuse to pay for.',
      'Budget pacing including VAT — Saudi ad spend carries 15% VAT. We plan for it so your budget means what you think it means.',
      'Monthly reporting — spend, clicks, cost per lead, conversions, and what changed.',
    ],
    deliverablesAr: [
      'بحث كلمات ثنائي اللغة — بالعربية والإنجليزية. لا يكون البحث العربي ترجمة للبحث الإنجليزي. يستخدم الناس اللهجة والكتابة اللاتينية والاختصارات التي لن تكشفها أي قائمة كلمات إنجليزية.',
      'بناء الحملات — بحث، وPerformance Max، وYouTube، وشبكة العرض، وإعادة الاستهداف، نختارها لعملك بدل تشغيلها افتراضيًا.',
      'نصوص إعلانية باللغتين — نكتبها أصالةً ونختبرها باستمرار.',
      'تتبع تحويلات يعمل فعلًا — GA4، وإجراءات التحويل، وتتبع المكالمات، وتتبع نقرات واتساب. يتحوّل المشتري السعودي عبر واتساب أكثر بكثير من النماذج، والحساب الذي يحصي النماذج فقط يكذب عليك بشأن أدائه.',
      'استراتيجية صفحات الهبوط — نبني الصفحات أيضًا. وإذا كانت صفحتك هي العائق، نصلحها بدل أن نكتب عنها تقريرًا.',
      'إدارة الكلمات السلبية — باستمرار، لأن نصف عمل إعلانات Google هو تحديد ما ترفض الدفع مقابله.',
      'ضبط الميزانية شاملًا الضريبة — يحمل الإنفاق الإعلاني في السعودية ضريبة قيمة مضافة 15%. نخطط لها لتعني ميزانيتك ما تظنه.',
      'تقرير شهري — الإنفاق والنقرات وتكلفة العميل المحتمل والتحويلات وما تغيّر.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what a customer is worth to you, what you want to spend, what a good month looks like.' },
      { label: 'Account audit or build', text: 'if you have an account, we audit it and show you what is broken before we touch anything. If you do not, we build it in your name.' },
      { label: 'Launch', text: 'campaigns live with tracking verified before spend starts. Never the other way around.' },
      { label: 'Optimize', text: 'search terms, bids, creative, and landing pages, continuously.' },
      { label: 'Report', text: 'monthly numbers, plainly stated.' },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'كم يساوي العميل بالنسبة لك، وكم تريد أن تنفق، وكيف يبدو الشهر الجيد.' },
      { label: 'تدقيق أو بناء الحساب', text: 'إن كان لديك حساب، ندققه ونعرض عليك ما هو معطوب قبل أن نلمس شيئًا. وإن لم يكن، نبنيه باسمك.' },
      { label: 'الإطلاق', text: 'تنطلق الحملات بعد التحقق من التتبع، لا قبله.' },
      { label: 'التحسين', text: 'مصطلحات البحث والمزايدات والإبداع وصفحات الهبوط، باستمرار.' },
      { label: 'التقرير', text: 'أرقام شهرية، بلا تجميل.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Healthcare and clinics · Real estate · Legal and professional services · Home services · Automotive · Education · B2B and industrial · E-commerce',
    industriesAr: 'الرعاية الصحية والعيادات · العقار · الخدمات القانونية والمهنية · خدمات المنازل · السيارات · التعليم · الأعمال والصناعة · المتاجر الإلكترونية',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: 'Most Google Ads agencies stop at the click. We are also the company that builds the website the click lands on — 25+ platforms built and running. When the problem is your landing page, and it usually is, we can actually fix it.',
    whyPremieraAr: 'تتوقف معظم وكالات إعلانات Google عند النقرة. ونحن أيضًا الشركة التي تبني الموقع الذي تصل إليه النقرة — أكثر من 25 منصة بنيناها ونشغّلها. وحين تكون صفحة الهبوط هي المشكلة، وهي كذلك غالبًا، نستطيع إصلاحها فعلًا.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'Ad copy is written to Saudi advertising standards. No claims we cannot support, no misleading offers, no fabricated urgency. If a claim you want to run cannot be substantiated, we will say so before it goes live rather than after a regulator asks.',
    complianceAr: 'نكتب النصوص الإعلانية وفق معايير الإعلان في المملكة. بلا ادعاءات لا نستطيع إثباتها، وبلا عروض مضللة، وبلا إلحاح مفتعل. وإن كان ادعاء تريد تشغيله غير قابل للإثبات، نقول لك ذلك قبل بثه لا بعد أن يسأل الجهة التنظيمية.',
    faqsEn: [
      { q: 'What budget do I need for Google Ads in Saudi Arabia?', a: 'It depends on your industry, your competition, and what a customer is worth to you. Cost per click in Saudi legal or real estate looks nothing like a local service business. We work this out with you in the strategy session, against real numbers rather than a generic figure.' },
      { q: 'Who owns the Google Ads account?', a: 'You do. It is created in your name, you have admin access, and it stays with you. Agencies that keep the account hostage are protecting themselves, not you.' },
      { q: 'Can you take over our existing account?', a: 'Yes. We audit it first and show you what we found before changing anything. Sometimes the existing structure is worth keeping.' },
      { q: 'Do you run ads in Arabic or English?', a: 'Both, where both make sense. Most Saudi accounts should be Arabic-led with English support, but it depends on your customer.' },
      { q: 'Is ad spend included in your fee?', a: 'No. Ad spend goes directly to Google from your account, and our management is separate. You always see exactly what Google was paid.' },
      { q: 'How long before we see results?', a: 'Search campaigns can produce leads in the first week. Getting cost per lead to a good place typically takes two to three months of data and iteration. We do not promise a number.' },
      { q: 'Do you build the landing pages too?', a: 'Yes. That is our Digital Experiences division — custom-coded, fast, and built to convert rather than a template.' },
      { q: 'Do you report on ad spend?', a: 'Every month, fully. Spend, cost per lead, conversions, and what we changed. No vanity metrics.' },
    ],
    faqsAr: [
      { q: 'ما الميزانية التي أحتاجها لإعلانات Google في السعودية؟', a: 'يعتمد ذلك على قطاعك ومنافستك وقيمة العميل بالنسبة لك. لا تشبه تكلفة النقرة في القطاع القانوني أو العقاري ما تدفعه خدمة محلية. نحدد ذلك معك في الجلسة الاستراتيجية بأرقام حقيقية، لا برقم عام.' },
      { q: 'من يملك حساب إعلانات Google؟', a: 'تملكه أنت. يُنشأ باسمك، ولديك صلاحية المدير، ويبقى معك. والوكالات التي تحتجز الحساب تحمي نفسها لا تحميك.' },
      { q: 'هل يمكنكم تسلّم حسابنا الحالي؟', a: 'نعم. ندققه أولًا ونعرض عليك ما وجدناه قبل تغيير أي شيء. وأحيانًا يستحق البناء القائم البقاء.' },
      { q: 'هل تشغّلون الإعلانات بالعربية أم الإنجليزية؟', a: 'بالاثنتين حين يكون لهما معنى. ينبغي أن تقود العربية معظم الحسابات السعودية بدعم إنجليزي، لكن ذلك يعتمد على عميلك.' },
      { q: 'هل الإنفاق الإعلاني ضمن أتعابكم؟', a: 'لا. يذهب الإنفاق مباشرة إلى Google من حسابك، وإدارتنا منفصلة. ترى دائمًا ما دُفع لـGoogle بالضبط.' },
      { q: 'متى نرى النتائج؟', a: 'قد تنتج حملات البحث عملاء محتملين في الأسبوع الأول. أما الوصول بتكلفة العميل المحتمل إلى مستوى جيد فيستغرق عادة شهرين إلى ثلاثة من البيانات والتحسين. لا نعدك برقم.' },
      { q: 'هل تبنون صفحات الهبوط أيضًا؟', a: 'نعم. ذلك قسم التجارب الرقمية لدينا — مبرمج بالكامل، وسريع، ومبني للتحويل لا قالب جاهز.' },
      { q: 'هل تقدّمون تقارير عن الإنفاق؟', a: 'كل شهر، بالكامل. الإنفاق وتكلفة العميل المحتمل والتحويلات وما غيّرناه. بلا أرقام شكلية.' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'seo-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'facebook-instagram-ads-saudi',
    titleEn: 'Facebook & Instagram Ads in Saudi Arabia',
    titleAr: 'إعلانات فيسبوك وإنستغرام في السعودية',
    descEn: 'Meta ads managed for Saudi businesses — Arabic creative, proper pixel and conversions API setup, and monthly reporting on every riyal spent.',
    descAr: 'ندير إعلانات Meta للشركات السعودية — محتوى عربي ننتجه بأنفسنا، وإعداد سليم للبكسل وواجهة التحويلات، وتقارير شهرية عن كل ريال.',
    metaTitleEn: 'Facebook & Instagram Ads in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إعلانات فيسبوك وإنستغرام في السعودية | بريميرا لايف',
    metaDescEn: 'Meta ads managed for Saudi businesses — Arabic creative, proper pixel and conversions API setup, and monthly reporting on every riyal spent.',
    metaDescAr: 'ندير إعلانات Meta للشركات السعودية — محتوى عربي ننتجه بأنفسنا، وإعداد سليم للبكسل وواجهة التحويلات، وتقارير شهرية عن كل ريال.',
    heroEn: 'On Google, people search for you. On Instagram, you have to earn the stop. Meta advertising is won or lost on creative — and creative is the one thing most ad agencies quietly outsource. We shoot it ourselves.',
    heroAr: 'يبحث الناس عنك على Google. أما على إنستغرام فعليك أن تستحق التوقف. تُربح إعلانات Meta أو تُخسر بالمحتوى الإبداعي — وهو الشيء الوحيد الذي تُسنده معظم الوكالات بهدوء إلى غيرها. نصوّره بأنفسنا.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: "Meta's targeting is no longer the advantage it was. Since the iOS privacy changes, the platform leans far harder on creative signals than on audience settings. Which means the agency running your account can have perfect campaign structure and still fail, because the video is boring.\n\nThe businesses winning on Instagram in Saudi Arabia are not the ones with the cleverest targeting. They are the ones producing enough good creative, often enough, to keep testing.",
    whyAr: 'لم يعد استهداف Meta الميزة التي كان عليها. فمنذ تغييرات الخصوصية في iOS، تعتمد المنصة على إشارات المحتوى الإبداعي أكثر بكثير من إعدادات الجمهور. ما يعني أن الشركة التي تدير حسابك قد تملك بنية حملات مثالية وتفشل رغم ذلك، لأن الفيديو ممل.\n\nالشركات التي تربح على إنستغرام في السعودية ليست صاحبة الاستهداف الأذكى، بل التي تنتج محتوى جيدًا بكمية وتكرار يكفيان لمواصلة الاختبار.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Meta Business Manager setup — properly configured, in your name, with the right permissions and asset ownership.',
      'Pixel and Conversions API — server-side tracking so you are not flying blind on iOS traffic. This is where most Saudi accounts are quietly broken.',
      'Creative production — video, photography, and design produced in-house by our film crew. Vertical-first, sound-on, built for the feed and for Reels.',
      'Arabic and English creative — captions and on-screen text written natively in both.',
      'Campaign structure — prospecting, retargeting, and lookalikes, structured so you can actually tell what is working.',
      'Click-to-WhatsApp campaigns — Saudi buyers overwhelmingly prefer messaging over forms. We build for how people here actually buy.',
      'Catalogue and shopping setup for e-commerce and retail.',
      'Continuous creative testing — new angles every month, because Meta creative fatigues fast.',
      'Monthly reporting — spend, cost per result, best and worst creative, and what is next.',
    ],
    deliverablesAr: [
      'إعداد Meta Business Manager — مضبوط بشكل صحيح، باسمك، بالصلاحيات وملكية الأصول الصحيحة.',
      'البكسل وواجهة التحويلات (CAPI) — تتبع من جهة الخادم حتى لا تعمل في العتمة مع زوار iOS. وهنا تحديدًا تكون معظم الحسابات السعودية معطوبة بصمت.',
      'إنتاج المحتوى — فيديو وتصوير وتصميم ننتجه داخليًا بفريق أفلامنا. عمودي أولًا، بصوت، ومبني للفيد وللريلز.',
      'محتوى بالعربية والإنجليزية — التعليقات والنصوص على الشاشة مكتوبة أصالةً باللغتين.',
      'بنية الحملات — استكشاف وإعادة استهداف وجماهير مشابهة، مبنية بحيث تعرف فعلًا ما الذي ينجح.',
      'حملات النقر إلى واتساب — يفضّل المشتري السعودي المراسلة على النماذج بفارق كبير. نبني وفق طريقة الشراء هنا فعلًا.',
      'إعداد الكتالوج والتسوق للتجزئة والمتاجر الإلكترونية.',
      'اختبار إبداعي مستمر — زوايا جديدة كل شهر، لأن محتوى Meta يستهلك نفسه سريعًا.',
      'تقرير شهري — الإنفاق وتكلفة النتيجة وأفضل وأسوأ محتوى وما التالي.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'audience, offer, and what a conversion is worth.' },
      { label: 'Technical setup', text: 'Business Manager, pixel, Conversions API, catalogue. Verified before spend.' },
      { label: 'Creative production', text: 'shot in a planned batch so the account never runs dry.' },
      { label: 'Launch and test', text: 'structured testing, not guessing.' },
      { label: 'Report and iterate', text: "monthly numbers and next month's creative plan." },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'الجمهور والعرض وقيمة التحويل.' },
      { label: 'الإعداد التقني', text: 'Business Manager والبكسل وواجهة التحويلات والكتالوج. نتحقق منها قبل الإنفاق.' },
      { label: 'إنتاج المحتوى', text: 'نصوّره دفعة مخططة حتى لا يجف الحساب.' },
      { label: 'الإطلاق والاختبار', text: 'اختبار منظم، لا تخمين.' },
      { label: 'التقرير والتكرار', text: 'أرقام شهرية وخطة المحتوى للشهر التالي.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Restaurants and F&B · Retail and e-commerce · Beauty and wellness · Hotels and hospitality · Healthcare · Real estate · Education',
    industriesAr: 'المطاعم والأغذية · التجزئة والمتاجر الإلكترونية · التجميل والعناية · الفنادق والضيافة · الرعاية الصحية · العقار · التعليم',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: "Ad agencies brief creative. We produce it. Our Cinematic Production division shoots commercial films for global brands, and that is the same crew producing your Meta creative — 20+ global brands, 1,000+ projects.\n\nThe practical difference: when creative fatigues in week three, we can shoot new assets. We are not waiting on a freelancer's availability.",
    whyPremieraAr: 'ترسل الوكالات بريفات المحتوى. ونحن ننتجه. يصوّر قسم الإنتاج السينمائي لدينا أفلامًا تجارية لعلامات عالمية، وهو الفريق نفسه الذي ينتج محتوى Meta الخاص بك — أكثر من 20 علامة عالمية، وأكثر من 1,000 مشروع.\n\nوالفارق العملي: حين يستهلك المحتوى نفسه في الأسبوع الثالث، نصوّر أصولًا جديدة. لا ننتظر توفّر مصوّر مستقل.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'All creative is produced to Saudi advertising standards — modest dress, no wealth flaunting, no children in promotional content. Paid partnerships are disclosed. Creator collaborations run exclusively through Mawthooq-licensed influencers. We do not use the WhatsApp or Meta logos in ways that breach their trademark guidelines.',
    complianceAr: 'ننتج كل محتوى وفق معايير الإعلان في المملكة — لباس محتشم، وبلا استعراض للثراء، وبلا أطفال في المحتوى الترويجي. نفصح عن الشراكات المدفوعة. ونعمل مع صنّاع المحتوى حصريًا عبر مرخّصين في منصة موثوق. ولا نستخدم شعارات واتساب أو Meta بما يخالف إرشادات علاماتها التجارية.',
    faqsEn: [
      { q: 'Facebook or Instagram — which should we be on?', a: 'Both are bought through the same platform, so it is rarely either/or. The real question is which placements deserve your budget, and that depends on your audience.' },
      { q: 'Who owns the ad account and the pixel?', a: 'You do. Everything is created inside your Business Manager, in your name.' },
      { q: 'Do you produce the video and photos?', a: 'Yes, in-house. That is the core of what we do.' },
      { q: 'What about the iOS tracking changes?', a: 'We implement the Conversions API so conversions are tracked server-side. If your current account only runs the browser pixel, it is under-reporting and over-paying.' },
      { q: 'Can you run click-to-WhatsApp ads?', a: 'Yes. For many Saudi businesses this outperforms form-fill campaigns significantly.' },
      { q: 'Do you work with influencers?', a: 'Only Mawthooq-licensed creators. Non-negotiable.' },
      { q: 'How much creative do you need per month?', a: 'Enough to keep testing without fatiguing. That is set in your plan, and it is the single biggest factor in Meta performance.' },
      { q: 'Do you guarantee a cost per lead?', a: 'No. Anyone who does is either guessing or planning to move the goalposts. We commit to transparent reporting and continuous iteration.' },
    ],
    faqsAr: [
      { q: 'فيسبوك أم إنستغرام — أيهما نختار؟', a: 'تُشترى الاثنتان عبر المنصة نفسها، فنادرًا ما يكون الأمر اختيارًا بينهما. السؤال الحقيقي: أي المواضع تستحق ميزانيتك، وذلك يعتمد على جمهورك.' },
      { q: 'من يملك الحساب الإعلاني والبكسل؟', a: 'تملكهما أنت. يُنشأ كل شيء داخل Business Manager الخاص بك، باسمك.' },
      { q: 'هل تنتجون الفيديو والصور؟', a: 'نعم، داخليًا. وهذا جوهر ما نفعله.' },
      { q: 'ماذا عن تغييرات التتبع في iOS؟', a: 'ننفّذ واجهة التحويلات (CAPI) ليُتتبع التحويل من جهة الخادم. وإن كان حسابك الحالي يعتمد على بكسل المتصفح فقط، فهو يُبلّغ بأقل من الواقع ويدفع أكثر منه.' },
      { q: 'هل تشغّلون حملات النقر إلى واتساب؟', a: 'نعم. تتفوق لدى كثير من الشركات السعودية على حملات النماذج بفارق واضح.' },
      { q: 'هل تتعاونون مع المؤثرين؟', a: 'مع مرخّصي منصة موثوق فقط. غير قابل للتفاوض.' },
      { q: 'كم محتوى تحتاجون شهريًا؟', a: 'ما يكفي لمواصلة الاختبار دون استهلاك. نحدده في خطتك، وهو العامل الأكبر منفردًا في أداء Meta.' },
      { q: 'هل تضمنون تكلفة عميل محتمل معينة؟', a: 'لا. من يضمنها إما يخمّن أو ينوي تحريك الأهداف لاحقًا. نلتزم بتقارير شفافة وتحسين مستمر.' },
    ],
    relatedSlugs: ['snapchat-tiktok-ads-saudi', 'content-production-saudi', 'social-media-management-saudi', 'google-ads-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'snapchat-tiktok-ads-saudi',
    titleEn: 'Snapchat & TikTok Ads in Saudi Arabia',
    titleAr: 'إعلانات سناب شات وتيك توك في السعودية',
    descEn: 'Snapchat and TikTok advertising for Saudi businesses — vertical creative shot in-house, campaign management, and monthly reporting. No repurposed landscape video.',
    descAr: 'ننتج ونشغّل إعلانات سناب شات وتيك توك للشركات السعودية — محتوى عمودي نصوّره بأنفسنا، وإدارة حملات، وتقارير شهرية.',
    metaTitleEn: 'Snapchat & TikTok Ads in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إعلانات سناب شات وتيك توك في السعودية | بريميرا لايف',
    metaDescEn: 'Snapchat and TikTok advertising for Saudi businesses — vertical creative shot in-house, campaign management, and monthly reporting. No repurposed landscape video.',
    metaDescAr: 'ننتج ونشغّل إعلانات سناب شات وتيك توك للشركات السعودية — محتوى عمودي نصوّره بأنفسنا، وإدارة حملات، وتقارير شهرية.',
    heroEn: 'Snapchat and TikTok are where young Saudi Arabia actually spends its attention. They are also where the most ad money gets wasted, because most brands treat them as a place to dump the landscape video they already made. Vertical video is not a crop. It is a format, and it has to be shot for the format.',
    heroAr: 'يقضي الشباب السعودي انتباهه فعليًا على سناب شات وتيك توك. وفيهما أيضًا يُهدر أكبر قدر من المال الإعلاني، لأن معظم العلامات تعاملهما كمكان لإلقاء الفيديو الأفقي الذي صوّرته أصلًا. الفيديو العمودي ليس قصًّا للإطار. إنه صيغة، ويجب أن يُصوَّر لها.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: "Snapchat's reach among young Saudi audiences is among the strongest of any market in the world. TikTok has become the default discovery engine for food, retail, and entertainment.\n\nNeither rewards polish for its own sake. They reward creative that looks like it belongs on the platform, hooks in the first two seconds, and works with the sound on. A beautifully graded brand film loses to a well-shot vertical clip every time in this feed.",
    whyAr: 'يُعد وصول سناب شات إلى الجمهور السعودي الشاب من الأقوى في أي سوق عالميًا. وأصبح تيك توك محرك الاكتشاف الافتراضي للمطاعم والتجزئة والترفيه.\n\nولا تكافئ أي منهما الإتقان لذاته. تكافئان محتوى يبدو أنه ينتمي إلى المنصة، ويخطف الانتباه في أول ثانيتين، ويعمل بالصوت. يخسر الفيلم المصحح لونيًا بإتقان أمام مقطع عمودي مصوَّر جيدًا في هذا الفيد، في كل مرة.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Vertical-native production — shot 9:16 from the start, sound-on, designed for a two-second hook.',
      'Snapchat campaigns — Snap Ads, Story Ads, Collection Ads, and AR lenses or geofilters where they earn their cost.',
      'TikTok campaigns — In-Feed, Spark Ads amplifying creator content, and Video Shopping where relevant.',
      'Arabic creative — on-screen text, voiceover, and captions in Arabic, written natively.',
      'Creator collaborations — through Mawthooq-licensed creators only.',
      'Pixel and event setup — Snap Pixel and TikTok Pixel, verified before launch.',
      'High creative volume — these platforms fatigue faster than any other. Volume is the strategy.',
      "Monthly reporting — spend, cost per result, top creative, next month's plan.",
    ],
    deliverablesAr: [
      'إنتاج عمودي أصيل — نصوّر بنسبة 9:16 من البداية، بصوت، ومصمم لخطف الانتباه في ثانيتين.',
      'حملات سناب شات — Snap Ads وStory Ads وCollection Ads وعدسات الواقع المعزز والفلاتر الجغرافية حين تستحق تكلفتها.',
      'حملات تيك توك — In-Feed وSpark Ads التي تضخّم محتوى صنّاع المحتوى، وVideo Shopping حين يكون مناسبًا.',
      'محتوى عربي — النصوص على الشاشة والتعليق الصوتي والترجمة بالعربية، مكتوبة أصالةً.',
      'التعاون مع صنّاع المحتوى — عبر مرخّصي منصة موثوق حصريًا.',
      'إعداد البكسل والأحداث — Snap Pixel وTikTok Pixel، نتحقق منهما قبل الإطلاق.',
      'كمية إنتاج عالية — تستهلك هاتان المنصتان المحتوى أسرع من غيرهما. الكمية هي الاستراتيجية.',
      'تقرير شهري — الإنفاق وتكلفة النتيجة وأفضل محتوى وخطة الشهر القادم.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'audience, platform fit, and what a result is worth. Not every business belongs on Snapchat.' },
      { label: 'Creative concepting', text: 'hooks and angles built for vertical, not adapted to it.' },
      { label: 'Production', text: 'batch-shot so the account has enough to test.' },
      { label: 'Launch and test', text: 'structured, with tracking verified first.' },
      { label: 'Report and refresh', text: 'new creative every cycle.' },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'الجمهور وملاءمة المنصة وقيمة النتيجة. لا ينتمي كل عمل إلى سناب شات.' },
      { label: 'بناء الأفكار', text: 'خطافات وزوايا مبنية للعمودي، لا مكيَّفة عليه.' },
      { label: 'الإنتاج', text: 'نصوّره دفعة واحدة ليملك الحساب ما يكفي للاختبار.' },
      { label: 'الإطلاق والاختبار', text: 'منظم، بعد التحقق من التتبع.' },
      { label: 'التقرير والتجديد', text: 'محتوى جديد كل دورة.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Restaurants and F&B · Retail and fashion · Beauty · Entertainment and events · Automotive · Education · Consumer apps',
    industriesAr: 'المطاعم والأغذية · التجزئة والأزياء · التجميل · الترفيه والفعاليات · السيارات · التعليم · التطبيقات الاستهلاكية',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: 'Most agencies running Snapchat in Saudi are media buyers who outsource creative. We are a production company that also buys the media. On these two platforms specifically, that is the whole ballgame — the creative is the campaign.',
    whyPremieraAr: 'معظم من يدير سناب شات في السعودية مشترو إعلانات يُسندون المحتوى إلى غيرهم. ونحن شركة إنتاج تشتري الإعلانات أيضًا. وعلى هاتين المنصتين تحديدًا، هذا هو كل شيء — المحتوى هو الحملة.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'Modest dress across all casting and imagery. No children in promotional content. No wealth or lifestyle flaunting. Ads labelled as advertising. Creator work exclusively through Mawthooq-licensed influencers — on platforms this creator-heavy, that is where most brands accumulate regulatory risk without realising it.',
    complianceAr: 'لباس محتشم في كل الاختيارات والصور. وبلا أطفال في المحتوى الترويجي. وبلا استعراض للثراء. نوسم الإعلانات بوصفها إعلانات. ونعمل مع صنّاع المحتوى حصريًا عبر مرخّصي منصة موثوق — وعلى منصات يقودها صنّاع المحتوى بهذا القدر، هنا تتراكم المخاطر التنظيمية على العلامات دون أن تنتبه.',
    faqsEn: [
      { q: 'Is Snapchat still worth it in Saudi Arabia?', a: 'For consumer brands targeting younger audiences, it remains one of the strongest channels in this market. For B2B and industrial, usually not — and we will tell you that rather than take the budget.' },
      { q: 'Can you use our existing video?', a: 'If it was shot landscape, we would rather not. Cropped landscape video underperforms native vertical badly enough that it is usually cheaper to shoot properly.' },
      { q: 'Do you make AR lenses and filters?', a: 'Yes, where they make sense for the campaign. They are not right for every brand.' },
      { q: 'Do you work with TikTok creators?', a: 'Yes — Mawthooq-licensed only, briefed and managed by us.' },
      { q: 'How fast does creative burn out?', a: 'Faster than any other platform. Plan for a continuous refresh cycle rather than one hero video.' },
      { q: 'Who owns the ad accounts?', a: 'You do, in your name, with your access.' },
      { q: 'Can you handle both platforms together?', a: 'Yes. The creative approach overlaps enough to produce for both in one shoot, which is usually the efficient route.' },
    ],
    faqsAr: [
      { q: 'هل ما زال سناب شات يستحق في السعودية؟', a: 'للعلامات الاستهلاكية التي تستهدف جمهورًا أصغر سنًا، يبقى من أقوى القنوات في هذا السوق. أما للأعمال والصناعة فغالبًا لا — وسنقول لك ذلك بدل أخذ الميزانية.' },
      { q: 'هل يمكنكم استخدام الفيديو الموجود لدينا؟', a: 'إن كان مصوَّرًا أفقيًا، نفضّل ألا نفعل. يقلّ أداء الفيديو الأفقي المقصوص عن العمودي الأصيل بما يكفي ليكون التصوير الصحيح أرخص عادة.' },
      { q: 'هل تصنعون عدسات وفلاتر الواقع المعزز؟', a: 'نعم، حين تناسب الحملة. وهي ليست مناسبة لكل علامة.' },
      { q: 'هل تتعاونون مع صنّاع محتوى تيك توك؟', a: 'نعم — مرخّصي منصة موثوق فقط، نبرّفهم وندير التعاون بأنفسنا.' },
      { q: 'كم يستهلك المحتوى نفسه؟', a: 'أسرع من أي منصة أخرى. خطط لدورة تجديد مستمرة بدل فيديو بطولي واحد.' },
      { q: 'من يملك الحسابات الإعلانية؟', a: 'تملكها أنت، باسمك وبصلاحياتك.' },
      { q: 'هل يمكنكم إدارة المنصتين معًا؟', a: 'نعم. يتداخل النهج الإبداعي بما يكفي للإنتاج للمنصتين في تصوير واحد، وهو الطريق الأكفأ عادة.' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'content-production-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'seo-saudi',
    titleEn: 'SEO in Saudi Arabia',
    titleAr: 'تحسين محركات البحث في السعودية',
    descEn: 'SEO for Saudi businesses — Arabic and English search, technical fixes, local search, and content built to rank. We build the site too, so fixes actually ship.',
    descAr: 'نحسّن ظهور الشركات السعودية في البحث — بالعربية والإنجليزية، وإصلاحات تقنية، وبحث محلي، ومحتوى مبني ليتصدر. نبني الموقع أيضًا.',
    metaTitleEn: 'SEO in Saudi Arabia | Arabic & English Search | Premiera Live',
    metaTitleAr: 'تحسين محركات البحث في السعودية | بحث عربي وإنجليزي | بريميرا لايف',
    metaDescEn: 'SEO for Saudi businesses — Arabic and English search, technical fixes, local search, and content built to rank. We build the site too, so fixes actually ship.',
    metaDescAr: 'نحسّن ظهور الشركات السعودية في البحث — بالعربية والإنجليزية، وإصلاحات تقنية، وبحث محلي، ومحتوى مبني ليتصدر. نبني الموقع أيضًا.',
    heroEn: 'Ads stop the day you stop paying. Search compounds. SEO is the slowest channel we offer and the only one that keeps working after the budget ends — which is exactly why it is worth starting before you need it.',
    heroAr: 'تتوقف الإعلانات يوم تتوقف عن الدفع. أما البحث فيتراكم. يُعد تحسين محركات البحث أبطأ قناة نقدّمها، والوحيدة التي تستمر بعد انتهاء الميزانية — ولهذا تحديدًا يستحق أن تبدأه قبل أن تحتاجه.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: 'Two things break SEO in Saudi Arabia more than anything else.\n\nThe first is treating Arabic SEO as translated English SEO. Saudis search in Arabic, in dialect, with transliteration and shorthand that no English keyword list contains. The Arabic query and the English query for the same service are often two completely different pieces of content.\n\nThe second is that most agencies can only recommend fixes. They send a technical audit to your web developer, your developer is busy, and eighteen months later the same issues are still there. We build the site, so we ship the fix.',
    whyAr: 'يكسر أمران تحسين محركات البحث في السعودية أكثر من أي شيء آخر.\n\nالأول: معاملة السيو العربي كترجمة للسيو الإنجليزي. يبحث السعوديون بالعربية، وباللهجة، وبالكتابة اللاتينية والاختصارات التي لا تحتويها أي قائمة كلمات إنجليزية. وغالبًا ما يكون الاستعلام العربي والإنجليزي للخدمة نفسها محتويين مختلفين تمامًا.\n\nالثاني: لا تستطيع معظم الوكالات إلا التوصية بالإصلاحات. ترسل تدقيقًا تقنيًا إلى مطوّرك، ويكون مطوّرك مشغولًا، وبعد ثمانية عشر شهرًا تبقى المشكلات نفسها. نحن نبني الموقع، فننفّذ الإصلاح.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Bilingual keyword research — Arabic and English, mapped to real search behaviour rather than translated word lists.',
      'Technical SEO — crawlability, indexation, site speed, Core Web Vitals, correct RTL rendering, and hreflang for ar-SA and en-SA. Bilingual sites break in specific, predictable ways.',
      'On-page optimization — titles, meta descriptions, headings, internal linking, and structured data.',
      'Content clusters — comprehensive coverage of a topic with pages that link to each other, instead of scattered one-off pages competing with themselves.',
      'Local SEO — Google Business Profile for Riyadh, Jeddah, Khobar, Dammam, Jubail, and the Eastern Province, with genuinely distinct content per location rather than duplicated city pages.',
      'Schema markup — organization, service, FAQ, local business, article.',
      'Monthly reporting — rankings, traffic, and the queries actually bringing you business.',
    ],
    deliverablesAr: [
      'بحث كلمات ثنائي اللغة — بالعربية والإنجليزية، مربوط بسلوك بحث حقيقي لا بقوائم مترجمة.',
      'السيو التقني — الزحف والفهرسة وسرعة الموقع وCore Web Vitals وسلامة عرض RTL وhreflang لـ ar-SA و en-SA. تنكسر المواقع ثنائية اللغة بطرق محددة ومتوقعة.',
      'تحسين الصفحات — العناوين والأوصاف والترويسات والروابط الداخلية والبيانات المنظمة.',
      'عناقيد المحتوى — تغطية شاملة لموضوع بصفحات تترابط فيما بينها، بدل صفحات متفرقة تتنافس مع بعضها.',
      'البحث المحلي — Google Business Profile للرياض وجدة والخبر والدمام والجبيل والمنطقة الشرقية، بمحتوى مختلف فعليًا لكل موقع لا صفحات مدن مكررة.',
      'البيانات المنظمة (Schema) — المؤسسة والخدمة والأسئلة الشائعة والنشاط المحلي والمقالات.',
      'تقرير شهري — الترتيب والزيارات والاستعلامات التي تجلب لك عملًا فعلًا.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what you want to be found for, and who you are competing with.' },
      { label: 'Technical audit', text: 'what is broken, in priority order, with the business cost of each.' },
      { label: 'Fix and build', text: 'we implement rather than recommend.' },
      { label: 'Content', text: 'cluster by cluster, in both languages.' },
      { label: 'Report', text: 'monthly, with the honest picture.' },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'بماذا تريد أن تُعرف، ومن تنافس.' },
      { label: 'تدقيق تقني', text: 'ما هو معطوب، مرتبًا بالأولوية، مع كلفة كل عطل على العمل.' },
      { label: 'الإصلاح والبناء', text: 'ننفّذ بدل أن نوصي.' },
      { label: 'المحتوى', text: 'عنقودًا بعد عنقود، باللغتين.' },
      { label: 'التقرير', text: 'شهريًا، بالصورة الصادقة.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Healthcare · Real estate · Legal and professional services · Industrial and B2B · Education · Hospitality · E-commerce',
    industriesAr: 'الرعاية الصحية · العقار · الخدمات القانونية والمهنية · الصناعة والأعمال · التعليم · الضيافة · المتاجر الإلكترونية',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: 'We do not just advise on SEO — we run 25+ platforms of our own. BahrainNights, StudentPhotos, EventsBahrain and others are sites we built, rank, and operate. When we tell you something works, it is because we have done it on our own properties where there was no client to blame.',
    whyPremieraAr: 'لا نكتفي بالاستشارة في السيو — نشغّل أكثر من 25 منصة خاصة بنا. BahrainNights وStudentPhotos وEventsBahrain وغيرها مواقع بنيناها ورتّبناها ونديرها. وحين نقول لك إن شيئًا ينجح، فلأننا فعلناه على ممتلكاتنا حيث لا يوجد عميل نلومه.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'Content is written to Saudi advertising standards. We do not fabricate reviews, buy spam links, or use tactics that put your domain at risk for a short-term ranking. Everything we do to your site is something we would do to our own.',
    complianceAr: 'نكتب المحتوى وفق معايير الإعلان في المملكة. لا نلفّق تقييمات، ولا نشتري روابط مزعجة، ولا نستخدم أساليب تعرّض نطاقك للخطر مقابل ترتيب قصير الأجل. وكل ما نفعله بموقعك نفعله بمواقعنا.',
    faqsEn: [
      { q: 'How long does SEO take in Saudi Arabia?', a: 'Meaningful movement usually takes three to six months, and competitive terms take longer. Anyone promising page one in 30 days is selling something else.' },
      { q: "Do you guarantee number one rankings?", a: "No. Nobody can, and Google's own guidance says to distrust anyone who does. We commit to the work and transparent reporting." },
      { q: 'Is Arabic SEO different from English SEO?', a: 'Substantially. Different queries, different intent, different competition, and a set of technical issues specific to RTL and bilingual sites.' },
      { q: 'We already have a website — can you work with it?', a: 'Usually yes. If the platform itself is the obstacle — some page builders make real technical SEO impossible — we will tell you plainly rather than bill you for years of workarounds.' },
      { q: 'Do you build the pages you recommend?', a: 'Yes. That is the point.' },
      { q: 'What about backlinks?', a: 'Earned through real content and genuine relationships. We do not buy links. Bought links are a liability with a delayed fuse.' },
      { q: 'Do you do local SEO for multiple cities?', a: 'Yes — with genuinely different content for each city. Thin duplicated city pages get demoted, and they misrepresent your footprint.' },
      { q: 'Can you do SEO while the site is not yet public?', a: 'Yes. Architecture, content, and technical foundations are best built before launch, not retrofitted after.' },
    ],
    faqsAr: [
      { q: 'كم يستغرق تحسين محركات البحث في السعودية؟', a: 'يستغرق التحرك الملموس عادة من ثلاثة إلى ستة أشهر، وتستغرق المصطلحات التنافسية وقتًا أطول. ومن يعدك بالصفحة الأولى خلال 30 يومًا يبيعك شيئًا آخر.' },
      { q: 'هل تضمنون المركز الأول؟', a: 'لا. لا يستطيع أحد ذلك، وإرشادات Google نفسها تنصح بعدم الثقة بمن يعد به. نلتزم بالعمل وبتقارير شفافة.' },
      { q: 'هل يختلف السيو العربي عن الإنجليزي؟', a: 'اختلافًا كبيرًا. استعلامات مختلفة، ونية مختلفة، ومنافسة مختلفة، ومجموعة مشكلات تقنية خاصة بـRTL والمواقع ثنائية اللغة.' },
      { q: 'لدينا موقع بالفعل — هل تعملون عليه؟', a: 'عادة نعم. وإن كانت المنصة نفسها هي العائق — بعض أدوات البناء تجعل السيو التقني الحقيقي مستحيلًا — نقول لك ذلك بوضوح بدل محاسبتك على سنوات من الالتفاف.' },
      { q: 'هل تبنون الصفحات التي توصون بها؟', a: 'نعم. وهذا هو بيت القصيد.' },
      { q: 'ماذا عن الروابط الخلفية؟', a: 'نكسبها بمحتوى حقيقي وعلاقات حقيقية. لا نشتري الروابط. الروابط المشتراة التزام بفتيل مؤجل.' },
      { q: 'هل تقدّمون سيو محليًا لعدة مدن؟', a: 'نعم — بمحتوى مختلف فعليًا لكل مدينة. تُخفَّض صفحات المدن المكررة الضعيفة، وهي تعطي صورة غير صحيحة عن حضورك.' },
      { q: 'هل يمكن العمل على السيو قبل نشر الموقع؟', a: 'نعم. يُبنى الهيكل والمحتوى والأساس التقني قبل الإطلاق، لا يُركَّب بعده.' },
    ],
    relatedSlugs: ['google-ads-saudi', 'content-production-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'content-production-saudi',
    titleEn: 'Content Production in Saudi Arabia',
    titleAr: 'إنتاج المحتوى في السعودية',
    descEn: 'Video, photography, design, and Arabic copy produced in-house for Saudi brands — a month of content from a single planned shoot day.',
    descAr: 'ننتج الفيديو والتصوير والتصميم والنصوص العربية للعلامات السعودية داخليًا — محتوى شهر كامل من يوم تصوير واحد مخطط.',
    metaTitleEn: 'Content Production in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إنتاج المحتوى في السعودية | بريميرا لايف',
    metaDescEn: 'Video, photography, design, and Arabic copy produced in-house for Saudi brands — a month of content from a single planned shoot day.',
    metaDescAr: 'ننتج الفيديو والتصوير والتصميم والنصوص العربية للعلامات السعودية داخليًا — محتوى شهر كامل من يوم تصوير واحد مخطط.',
    heroEn: 'Every marketing plan dies in the same place: nobody has the content. The strategy is approved, the calendar is built, the ads are ready — and then someone has to actually shoot something. We are the part of the industry that shoots it.',
    heroAr: 'تموت كل خطة تسويق في المكان نفسه: لا أحد يملك المحتوى. تُعتمد الاستراتيجية، وتُبنى الروزنامة، وتُجهز الإعلانات — ثم يجب أن يصوّر أحدهم شيئًا فعلًا. نحن الجزء الذي يصوّره.',
    whyHeadingEn: 'Why This Matters',
    whyHeadingAr: 'لماذا يهم هذا',
    whyEn: 'Most agencies do not produce. They coordinate. The brief goes to a freelancer, the freelancer is busy, the shoot slips two weeks, and the campaign launches with stock footage and a stretched logo.\n\nWe are a film company first — 15+ years, 1,000+ projects, 20+ global brands. Content production is not a service we added to look complete. It is the thing we have always done, applied to the feed.',
    whyAr: 'لا تنتج معظم الوكالات. تنسّق. يذهب البريف إلى مصوّر مستقل، ويكون مشغولًا، فيتأخر التصوير أسبوعين، وتُطلق الحملة بلقطات أرشيفية وشعار ممدود.\n\nنحن شركة أفلام أولًا — أكثر من 15 عامًا، وأكثر من 1,000 مشروع، وأكثر من 20 علامة عالمية. لم نضف إنتاج المحتوى لنبدو مكتملين. هو ما نفعله منذ البداية، مطبَّقًا على الفيد.',
    deliverablesHeadingEn: 'What We Deliver',
    deliverablesHeadingAr: 'ما نقدمه',
    deliverablesEn: [
      'Monthly content shoot days — one planned day producing a month of assets across video, photography, and design.',
      'Vertical-first video — shot 9:16 for Reels, Snapchat, TikTok, and Shorts, with landscape versions where you need them.',
      'Professional photography — product, food, interior, portrait, and event, shot by photographers who do this for global brands.',
      'Motion graphics and design — titles, lower thirds, carousels, and static posts, built to your brand.',
      'Arabic and English copy — written natively in both.',
      'Animation and CGI — where the shot cannot be filmed, our Animation division builds it.',
      'Full asset delivery — every file, every crop, every version, yours to keep.',
    ],
    deliverablesAr: [
      'أيام تصوير شهرية — يوم واحد مخطط ينتج محتوى شهر كامل من فيديو وتصوير وتصميم.',
      'فيديو عمودي أولًا — نصوّر 9:16 للريلز وسناب شات وتيك توك واليوتيوب شورتس، مع نسخ أفقية عند الحاجة.',
      'تصوير فوتوغرافي احترافي — منتجات وأطعمة وديكور وبورتريه وفعاليات، يصوّره مصوّرون يعملون لعلامات عالمية.',
      'موشن جرافيك وتصميم — عناوين وشرائط سفلية وكاروسيل ومنشورات ثابتة، مبنية على هويتك.',
      'نصوص بالعربية والإنجليزية — مكتوبة أصالةً باللغتين.',
      'رسوم متحركة وCGI — حين يتعذّر تصوير اللقطة، يبنيها قسم الرسوم المتحركة لدينا.',
      'تسليم كامل للأصول — كل ملف، وكل قصّ، وكل نسخة، ملك لك.',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what content your channels actually need each month, and in what volume.' },
      { label: 'Shot list', text: 'planned against your content calendar and approved by you before the crew moves.' },
      { label: 'Production day', text: 'one efficient day, batch-shot. This is where the cost efficiency comes from.' },
      { label: 'Post-production', text: 'edit, grade, sound, graphics, and versioning for each platform.' },
      { label: 'Delivery', text: 'organized, named, and ready to publish.' },
    ],
    processStepsAr: [
      { label: 'جلسة استراتيجية', text: 'ما المحتوى الذي تحتاجه قنواتك فعلًا كل شهر، وبأي كمية.' },
      { label: 'قائمة اللقطات', text: 'مخططة وفق روزنابة المحتوى وتوافق عليها قبل تحرّك الفريق.' },
      { label: 'يوم الإنتاج', text: 'يوم واحد كفؤ، بتصوير مجمّع. ومن هنا تأتي كفاءة التكلفة.' },
      { label: 'ما بعد الإنتاج', text: 'مونتاج وتصحيح ألوان وصوت وجرافيك ونسخ لكل منصة.' },
      { label: 'التسليم', text: 'منظم ومسمّى وجاهز للنشر.' },
    ],
    industriesHeadingEn: 'Industries We Serve',
    industriesHeadingAr: 'القطاعات التي نخدمها',
    industriesEn: 'Restaurants and F&B · Hotels and hospitality · Retail and fashion · Healthcare · Real estate · Automotive · Industrial and manufacturing · Events',
    industriesAr: 'المطاعم والأغذية · الفنادق والضيافة · التجزئة والأزياء · الرعاية الصحية · العقار · السيارات · الصناعة والتصنيع · الفعاليات',
    whyPremieraHeadingEn: 'Why Premiera Live',
    whyPremieraHeadingAr: 'لماذا بريميرا لايف',
    whyPremieraEn: "Our crew shoots commercial films. The same people, cameras, and lighting that produce a brand film produce your Instagram content. Most social content in this market is shot on a phone by an intern. Yours does not have to be.\n\nWe also handle the whole chain — strategy, production, publishing, and reporting — so nothing gets lost between three vendors blaming each other.",
    whyPremieraAr: 'يصوّر فريقنا أفلامًا تجارية. والأشخاص والكاميرات والإضاءة نفسها التي تنتج فيلم علامة تنتج محتوى إنستغرام الخاص بك. يُصوَّر معظم محتوى التواصل في هذا السوق بهاتف على يد متدرب. ولا يلزم أن يكون محتواك كذلك.\n\nوندير السلسلة كاملة — الاستراتيجية والإنتاج والنشر والتقارير — فلا يضيع شيء بين ثلاثة موردين يلوم بعضهم بعضًا.',
    complianceHeadingEn: 'Compliance-First',
    complianceHeadingAr: 'نلتزم أولًا، بحكم التصميم',
    complianceEn: 'Modest dress in all imagery and video. No children in promotional content. No wealth or lifestyle flaunting. Every production is planned to Saudi standards from the shot list stage, not fixed in the edit after somebody notices.',
    complianceAr: 'لباس محتشم في كل الصور والفيديو. وبلا أطفال في المحتوى الترويجي. وبلا استعراض للثراء. نخطط كل إنتاج وفق معايير المملكة من مرحلة قائمة اللقطات، لا نصلحه في المونتاج بعد أن ينتبه أحدهم.',
    faqsEn: [
      { q: 'How much content comes out of one shoot day?', a: 'That depends on the shot list and the setups, and it is planned in advance. Batch production is what makes a month of content from a single day realistic.' },
      { q: 'Do you shoot outside Riyadh?', a: 'Yes — across the Kingdom, and we travel. Our crew has worked across the GCC for 15+ years.' },
      { q: 'Can you shoot at our location?', a: 'Yes. Restaurants, clinics, factories, hotels, showrooms — location work is standard.' },
      { q: 'Do we own the footage?', a: 'Yes. Everything we shoot for you is yours, including the raw files if you want them.' },
    ],
    faqsAr: [
      { q: 'كم محتوى ينتج يوم تصوير واحد؟', a: 'يعتمد على قائمة اللقطات وعدد الإعدادات، ونخططه مسبقًا. التصوير المجمّع هو ما يجعل محتوى شهر من يوم واحد واقعيًا.' },
      { q: 'هل تصوّرون خارج الرياض؟', a: 'نعم — في أنحاء المملكة، ونسافر. عمل فريقنا في أنحاء الخليج لأكثر من 15 عامًا.' },
      { q: 'هل تصوّرون في موقعنا؟', a: 'نعم. المطاعم والعيادات والمصانع والفنادق والمعارض — التصوير الميداني معتاد لدينا.' },
      { q: 'هل نملك اللقطات؟', a: 'نعم. كل ما نصوّره لك ملك لك، بما في ذلك الملفات الخام إن أردتها.' },
    ],
    relatedSlugs: ['social-media-management-saudi', 'facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'google-ads-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'marketing-packages-saudi',
    titleEn: 'Growth Partnership Packages',
    titleAr: 'باقات شراكة النمو',
    descEn: 'Three growth partnership tiers — Foundation, Growth, and Scale. Monthly retainers covering strategy, content, advertising, SEO, and reporting.',
    descAr: 'نعمل بثلاث باقات شراكة للنمو — الأساس والنمو والريادة. اشتراكات شهرية تغطي الاستراتيجية والمحتوى والإعلانات وتحسين محركات البحث والتقارير.',
    metaTitleEn: 'Marketing Packages in Saudi Arabia | Premiera Live',
    metaTitleAr: 'باقات التسويق في السعودية | بريميرا لايف',
    metaDescEn: 'Three growth partnership tiers — Foundation, Growth, and Scale. Monthly retainers covering strategy, content, advertising, SEO, and reporting.',
    metaDescAr: 'نعمل بثلاث باقات شراكة للنمو — الأساس والنمو والريادة. اشتراكات شهرية تغطي الاستراتيجية والمحتوى والإعلانات وتحسين محركات البحث والتقارير.',
    heroEn: 'Marketing that works is not a campaign you run once. It is a partnership that compounds month after month. We work in three tiers — each one a complete system rather than a list of tasks. Where you start depends on where your business is, and we work that out together on a call.',
    heroAr: 'لا يكون التسويق الناجح حملة تُشغّلها مرة. يكون شراكة تتراكم شهرًا بعد شهر. نعمل بثلاث باقات، كل واحدة نظام متكامل لا قائمة مهام. ويعتمد أين تبدأ على موضع عملك اليوم، ونحدده معك في مكالمة.',
    whyHeadingEn: '',
    whyHeadingAr: '',
    whyEn: '',
    whyAr: '',
    deliverablesHeadingEn: '',
    deliverablesHeadingAr: '',
    deliverablesEn: [],
    deliverablesAr: [],
    processStepsEn: [],
    processStepsAr: [],
    industriesHeadingEn: '',
    industriesHeadingAr: '',
    industriesEn: '',
    industriesAr: '',
    whyPremieraHeadingEn: '',
    whyPremieraHeadingAr: '',
    whyPremieraEn: '',
    whyPremieraAr: '',
    complianceHeadingEn: '',
    complianceHeadingAr: '',
    complianceEn: '',
    complianceAr: '',
    faqsEn: [],
    faqsAr: [],
    relatedSlugs: ['social-media-management-saudi', 'google-ads-saudi', 'seo-saudi', 'content-production-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
    isPackages: true,
    packagesHeroEn: 'Marketing that works is not a campaign you run once. It is a partnership that compounds month after month. We work in three tiers — each one a complete system rather than a list of tasks. Where you start depends on where your business is, and we work that out together on a call.',
    packagesHeroAr: 'لا يكون التسويق الناجح حملة تُشغّلها مرة. يكون شراكة تتراكم شهرًا بعد شهر. نعمل بثلاث باقات، كل واحدة نظام متكامل لا قائمة مهام. ويعتمد أين تبدأ على موضع عملك اليوم، ونحدده معك في مكالمة.',
    packagesTiers: [
      {
        name: 'FOUNDATION',
        nameAr: 'الأساس',
        taglineEn: 'Establish your digital presence.',
        taglineAr: 'نؤسس حضورك الرقمي.',
        builtForEn: 'Startups · Restaurants · Cafés · Clinics · Small businesses · Retail stores',
        builtForAr: 'الشركات الناشئة · المطاعم · المقاهي · العيادات · الأعمال الصغيرة · متاجر التجزئة',
        deliverablesEn: [
          { category: 'Strategy', items: ['Initial marketing strategy session', 'Competitor analysis', 'Monthly content calendar', 'Brand direction'] },
          { category: 'Social Media', items: ['Up to 12 posts per month', 'Graphic design', 'Caption writing', 'Hashtag research', 'Content scheduling'] },
          { category: 'Google', items: ['Google Business Profile optimisation', 'Google Search Console monitoring', 'Google Analytics reporting'] },
          { category: 'Monthly Content', items: ['One half-day production session every month, covering:', 'Professional photography', 'Short-form video', 'Reels', 'Product photography'] },
          { category: 'Reporting', items: ['Monthly report: reach, engagement, website traffic, and recommendations'] },
          { category: 'Support', items: ['WhatsApp support during business hours', 'Monthly strategy meeting'] },
        ],
        deliverablesAr: [
          { category: 'الاستراتيجية', items: ['جلسة استراتيجية تسويقية أولى', 'تحليل المنافسين', 'خطة محتوى شهرية', 'توجيه الهوية'] },
          { category: 'وسائل التواصل الاجتماعي', items: ['حتى 12 منشورًا شهريًا', 'تصميم جرافيك', 'كتابة التعليقات', 'بحث الوسوم', 'جدولة المحتوى'] },
          { category: 'Google', items: ['تحسين Google Business Profile', 'متابعة Google Search Console', 'تقارير Google Analytics'] },
          { category: 'المحتوى الشهري', items: ['جلسة إنتاج نصف يوم كل شهر، تشمل:', 'تصوير فوتوغرافي احترافي', 'فيديو قصير', 'ريلز', 'تصوير المنتجات'] },
          { category: 'التقارير', items: ['تقرير شهري: الوصول والتفاعل وزيارات الموقع والتوصيات'] },
          { category: 'الدعم', items: ['دعم عبر واتساب خلال ساعات العمل', 'اجتماع استراتيجي شهري'] },
        ],
        notIncludedEn: 'Google Ads management · Website development · Website maintenance · SEO campaign',
        notIncludedAr: 'إدارة إعلانات Google · تطوير المواقع · صيانة المواقع · حملة تحسين محركات البحث',
      },
      {
        name: 'GROWTH',
        nameAr: 'النمو',
        taglineEn: 'Accelerate leads and sales.',
        taglineAr: 'نضاعف العملاء المحتملين والمبيعات.',
        builtForEn: 'SMEs · Manufacturers · Construction · Healthcare · Corporate companies · Hotels',
        builtForAr: 'المنشآت الصغيرة والمتوسطة · المصانع · المقاولات · الرعاية الصحية · الشركات · الفنادق',
        deliverablesEn: [
          { category: 'Everything in Foundation, plus:', items: [] },
          { category: 'Content', items: ['One full production day, covering:', 'Professional photography', 'Commercial video', 'Reels', 'Interviews', 'Behind the scenes', 'Product photography'] },
          { category: 'Performance Marketing', items: ['Google Ads management', 'Keyword research', 'Conversion tracking', 'Monthly optimisation', 'Remarketing', 'Landing page recommendations'] },
          { category: 'Technical SEO', items: ['Website audit', 'Search Console fixes', 'On-page optimisation', 'Performance optimisation', 'Monthly SEO reporting'] },
          { category: 'Analytics', items: ['Custom dashboards', 'Traffic analysis', 'Lead tracking', 'Campaign reporting', 'Return on investment review'] },
          { category: 'Strategy', items: ['Monthly strategy meeting', 'Campaign planning', 'Quarterly roadmap'] },
        ],
        deliverablesAr: [
          { category: 'كل ما في الأساس، إضافة إلى:', items: [] },
          { category: 'المحتوى', items: ['يوم إنتاج كامل، يشمل:', 'تصوير فوتوغرافي احترافي', 'فيديو تجاري', 'ريلز', 'مقابلات', 'كواليس', 'تصوير المنتجات'] },
          { category: 'التسويق بالأداء', items: ['إدارة إعلانات Google', 'بحث الكلمات', 'تتبع التحويلات', 'تحسين شهري', 'إعادة الاستهداف', 'توصيات صفحات الهبوط'] },
          { category: 'السيو التقني', items: ['تدقيق الموقع', 'إصلاحات Search Console', 'تحسين الصفحات', 'تحسين الأداء', 'تقرير سيو شهري'] },
          { category: 'التحليلات', items: ['لوحات مخصصة', 'تحليل الزيارات', 'تتبع العملاء المحتملين', 'تقارير الحملات', 'مراجعة العائد على الاستثمار'] },
          { category: 'الاستراتيجية', items: ['اجتماع استراتيجي شهري', 'تخطيط الحملات', 'خارطة طريق ربع سنوية'] },
        ],
        notIncludedEn: 'Premium website development · Custom software · CRM integrations. These are quoted separately.',
        notIncludedAr: 'غير مشمول: تطوير المواقع المتقدمة · البرمجيات المخصصة · تكامل أنظمة إدارة العملاء. تُسعّر منفصلة.',
      },
      {
        name: 'SCALE',
        nameAr: 'الريادة',
        taglineEn: 'Your dedicated growth partner.',
        taglineAr: 'نكون شريك نموك المخصص.',
        builtForEn: 'Large companies · Enterprise · Government · Luxury brands · Multi-location businesses',
        builtForAr: 'الشركات الكبرى · المؤسسات · الجهات الحكومية · العلامات الفاخرة · الأعمال متعددة الفروع',
        deliverablesEn: [
          { category: 'Everything in Growth, plus:', items: [] },
          { category: 'Dedicated Team', items: ['Dedicated account manager', 'Priority support', 'Monthly planning sessions', 'Quarterly business review', 'Marketing roadmap'] },
          { category: 'Production', items: ['Priority booking', 'Multiple production days', 'Commercial campaigns', 'Corporate photography', 'Executive portraits', 'Recruitment videos', 'Product launches'] },
          { category: 'Performance', items: ['Google Ads', 'Meta Ads (Facebook & Instagram)', 'Snapchat Ads', 'TikTok Ads', 'A/B testing', 'Conversion optimisation', 'Advanced reporting'] },
          { category: 'SEO', items: ['Advanced SEO strategy', 'Content planning', 'Technical monitoring', 'Competitor analysis', 'Local SEO'] },
          { category: 'Executive Reporting', items: ['Monthly executive dashboard', 'Campaign performance', 'Lead quality analysis', 'Growth recommendations', 'Quarterly planning presentation'] },
        ],
        deliverablesAr: [
          { category: 'كل ما في النمو، إضافة إلى:', items: [] },
          { category: 'فريق مخصص', items: ['مدير حساب مخصص', 'دعم ذو أولوية', 'جلسات تخطيط شهرية', 'مراجعة أعمال ربع سنوية', 'خارطة طريق تسويقية'] },
          { category: 'الإنتاج', items: ['حجز ذو أولوية', 'أيام إنتاج متعددة', 'حملات تجارية', 'تصوير الشركات', 'بورتريه تنفيذي', 'أفلام التوظيف', 'إطلاق المنتجات'] },
          { category: 'الأداء', items: ['إعلانات Google', 'إعلانات Meta (فيسبوك وإنستغرام)', 'إعلانات سناب شات', 'إعلانات تيك توك', 'اختبار A/B', 'تحسين التحويل', 'تقارير متقدمة'] },
          { category: 'تحسين محركات البحث', items: ['استراتيجية سيو متقدمة', 'تخطيط المحتوى', 'مراقبة تقنية', 'تحليل المنافسين', 'سيو محلي'] },
          { category: 'التقارير التنفيذية', items: ['لوحة تنفيذية شهرية', 'أداء الحملات', 'تحليل جودة العملاء المحتملين', 'توصيات النمو', 'عرض تخطيط ربع سنوي'] },
        ],
      },
    ],
    websiteDevEn: 'Website development is quoted separately.',
    websiteDevAr: 'نسعّر تطوير المواقع منفصلًا.',
    websiteDevItemsEn: [
      { heading: 'Website development is quoted separately.' },
      { paragraph: 'Websites are not included in any package. They are built by our Digital Experiences division and quoted per project:' },
      { items: ['Landing Pages', 'Business Websites', 'Premium Corporate Websites', 'Custom Business Platforms'] },
      { subHeading: 'Scale clients receive:' },
      { subItems: ['Priority scheduling', 'Preferential rates', 'Direct integration with their marketing strategy'] },
    ],
    websiteDevItemsAr: [
      { heading: 'نسعّر تطوير المواقع منفصلًا.' },
      { paragraph: 'لا تشمل أي باقة المواقع. يبنيها قسم التجارب الرقمية لدينا وتُسعّر لكل مشروع:' },
      { items: ['صفحات الهبوط', 'المواقع التجارية', 'المواقع المؤسسية المتقدمة', 'المنصات المخصصة للأعمال'] },
      { subHeading: 'يحصل عملاء الريادة على:' },
      { subItems: ['جدولة ذات أولوية', 'أسعار تفضيلية', 'تكامل مباشر مع استراتيجيتهم التسويقية'] },
    ],
    websiteCareEn: 'Website care can be added to any retainer.',
    websiteCareAr: 'تُضاف العناية بالموقع إلى أي اشتراك.',
    websiteCareItemsEn: [
      { heading: 'Website care can be added to any retainer.' },
      { paragraph: 'After launch, website support can be added to any package:' },
      { items: ['Hosting management', 'Security updates', 'Performance monitoring', 'Content updates', 'Technical support', 'Backups', 'Uptime monitoring', 'Minor improvements'] },
    ],
    websiteCareItemsAr: [
      { heading: 'تُضاف العناية بالموقع إلى أي اشتراك.' },
      { paragraph: 'بعد الإطلاق، يمكن إضافة دعم الموقع إلى أي باقة:' },
      { items: ['إدارة الاستضافة', 'تحديثات الأمان', 'مراقبة الأداء', 'تحديثات المحتوى', 'دعم تقني', 'نسخ احتياطية', 'مراقبة الجاهزية', 'تحسينات صغيرة'] },
    ],
    scaleBenefitsEn: [
      'Priority production scheduling',
      'Faster turnaround where feasible',
      'Quarterly website UX reviews',
      'Website maintenance included while under an active Scale retainer',
      'Reduced rates on future website rebuilds or major redesigns',
    ],
    scaleBenefitsAr: [
      'جدولة إنتاج ذات أولوية',
      'تسليم أسرع حيثما أمكن',
      'مراجعات ربع سنوية لتجربة الموقع',
      'صيانة الموقع مشمولة أثناء سريان اشتراك الريادة',
      'أسعار مخفّضة على إعادة بناء الموقع أو إعادة التصميم مستقبلًا',
    ],
    packagesFaqsEn: [
      { q: 'Which package is right for my business?', a: 'It depends on where you are and what you are trying to do. Foundation suits businesses building a consistent presence for the first time. Growth suits businesses ready to spend on advertising and want leads tracked properly. Scale suits organisations that need a dedicated team. We work it out on the call rather than pushing you up a tier.' },
      { q: 'Can I change packages later?', a: 'Yes. Most clients start at Foundation or Growth and move up as results justify it. Moving down is equally fine.' },
      { q: 'Is advertising spend included?', a: 'No. Ad spend goes directly to Google, Meta, Snapchat, or TikTok from your own accounts. Our management is separate, and you always see exactly what the platforms were paid.' },
      { q: 'Do you require annual contracts?', a: 'We recommend long-term partnerships because marketing results compound and a three-month engagement rarely shows what a channel can do. Every proposal is built around your goals rather than a fixed lock-in.' },
      { q: 'Who owns the accounts, content, and data?', a: 'You do. Accounts stay in your name, every asset we produce is yours, and nothing leaves with us.' },
      { q: 'Can I add website development to a package?', a: 'Yes, quoted separately. Scale clients get priority scheduling and preferential rates on it.' },
      { q: 'What is not included in any package?', a: 'Website development, custom software, and CRM integrations are always quoted separately.' },
      { q: 'Do you work outside Riyadh?', a: 'Yes — across the Kingdom, including Jeddah, Khobar, Dammam, Jubail, and the Eastern Province.' },
    ],
    packagesFaqsAr: [
      { q: 'أي باقة تناسب عملي؟', a: 'يعتمد ذلك على موضعك وما تحاول تحقيقه. يناسب الأساس من يبني حضورًا ثابتًا لأول مرة. ويناسب النمو من هو جاهز للإنفاق الإعلاني ويريد تتبع العملاء المحتملين بشكل صحيح. وتناسب الريادة الجهات التي تحتاج فريقًا مخصصًا. نحددها معك في المكالمة بدل دفعك إلى باقة أعلى.' },
      { q: 'هل يمكنني تغيير الباقة لاحقًا؟', a: 'نعم. يبدأ معظم العملاء بالأساس أو النمو ويصعدون حين تبرّر النتائج ذلك. والنزول مقبول تمامًا كذلك.' },
      { q: 'هل الإنفاق الإعلاني مشمول؟', a: 'لا. يذهب الإنفاق مباشرة إلى Google أو Meta أو سناب شات أو تيك توك من حساباتك. وإدارتنا منفصلة، وترى دائمًا ما دُفع للمنصات بالضبط.' },
      { q: 'هل تشترطون عقودًا سنوية؟', a: 'نوصي بشراكات طويلة الأمد لأن نتائج التسويق تتراكم، ونادرًا ما يُظهر ارتباط بثلاثة أشهر ما تستطيع القناة فعله. ويُبنى كل عرض حول أهدافك لا حول ارتباط ثابت.' },
      { q: 'من يملك الحسابات والمحتوى والبيانات؟', a: 'تملكها أنت. تبقى الحسابات باسمك، وكل أصل ننتجه ملك لك، ولا يخرج شيء معنا.' },
      { q: 'هل يمكن إضافة تطوير الموقع إلى الباقة؟', a: 'نعم، وتُسعّر منفصلة. ويحصل عملاء الريادة على جدولة ذات أولوية وأسعار تفضيلية عليها.' },
      { q: 'ما غير المشمول في أي باقة؟', a: 'تُسعّر تطوير المواقع والبرمجيات المخصصة وتكامل أنظمة إدارة العملاء منفصلة دائمًا.' },
      { q: 'هل تعملون خارج الرياض؟', a: 'نعم — في أنحاء المملكة، بما في ذلك جدة والخبر والدمام والجبيل والمنطقة الشرقية.' },
    ],
  },
]

export const MARKETING_SLUGS = SERVICES.map((s) => s.slug)

export function getMarketingService(slug: string): MarketingService | undefined {
  return SERVICES.find((s) => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): MarketingService[] {
  return SERVICES.filter((s) => slugs.includes(s.slug))
}

export function getServiceLabel(slug: string, isArabic: boolean): string {
  const s = getMarketingService(slug)
  if (!s) return slug
  return isArabic ? s.titleAr : s.titleEn
}
