export interface MarketingTier {
  name: string
  taglineEn: string
  taglineAr: string
  builtForEn: string
  builtForAr: string
  deliverablesEn: { category: string, items: string[] }[]
  deliverablesAr: { category: string, items: string[] }[]
  notIncludedEn?: string
  notIncludedAr?: string
}

export interface MarketingService {
  slug: string
  titleEn: string
  titleAr: string
  descEn: string
  descAr: string
  metaTitleEn: string
  metaTitleAr: string
  metaDescEn: string
  metaDescAr: string
  heroEn: string
  heroAr: string
  whyEn: string
  whyAr: string
  deliverablesEn: string[]
  deliverablesAr: string[]
  processStepsEn: { label: string; text: string }[]
  processStepsAr: { label: string; text: string }[]
  industriesEn: string
  industriesAr: string
  whyPremieraEn: string
  whyPremieraAr: string
  complianceEn: string
  complianceAr: string
  faqsEn: { q: string; a: string }[]
  faqsAr: { q: string; a: string }[]
  relatedSlugs: string[]
  ctaEn: string
  ctaAr: string
  // packages page fields
  isPackages?: true
  packagesHeroEn?: string
  packagesHeroAr?: string
  packagesTiers?: MarketingTier[]
  websiteDevEn?: string
  websiteDevAr?: string
  websiteDevItemsEn?: string[]
  websiteDevItemsAr?: string[]
  websiteCareEn?: string
  websiteCareAr?: string
  websiteCareItemsEn?: string[]
  websiteCareItemsAr?: string[]
  scaleBenefitsEn?: string[]
  scaleBenefitsAr?: string[]
  packagesFaqsEn?: { q: string; a: string }[]
  packagesFaqsAr?: { q: string; a: string }[]
}

const SERVICES: MarketingService[] = [
  {
    slug: 'social-media-management-saudi',
    titleEn: 'Social Media Management in Saudi Arabia',
    titleAr: 'إدارة وسائل التواصل الاجتماعي في المملكة العربية السعودية',
    descEn: 'We manage social media for Saudi businesses — Arabic-first content, daily publishing, community management, and monthly reporting.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Social Media Management in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إدارة وسائل التواصل الاجتماعي في السعودية | بريميرا لايف',
    metaDescEn: 'We manage social media for Saudi businesses — Arabic-first content, daily publishing, community management, and monthly reporting.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Most Saudi businesses do not have a social media problem. They have a consistency problem. Posting stops when the person who was posting gets busy, the feed goes quiet for three weeks, and the audience they spent months building forgets they exist. We run your social media as a monthly operation — planned in advance, published on schedule, answered every day, and reported at the end of every month.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: 'Your customers in Saudi Arabia are not browsing one platform. They are on Snapchat in the morning, TikTok at night, Instagram when they are shopping, and X when they are complaining. Each of those platforms has a different job, a different content format, and a different audience for your business.\n\nHanding all of it to one junior employee with a phone is how brands end up posting the same landscape graphic to four platforms and wondering why nothing happens. Handing it to an agency that translates English captions into stiff Modern Standard Arabic is how brands end up sounding like a government circular.\n\nWe plan each platform for what it actually does, produce content built for that format, and write in the language your audience uses.',
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Monthly content calendar — planned and approved by you before anything goes live. You always know what is publishing and when.',
      'Arabic-first copywriting — written in Arabic, not translated into it. English versions where your audience is bilingual.',
      'Platform-native content — vertical video for Snapchat and TikTok, carousels and reels for Instagram, short text for X. No landscape video squeezed into a vertical frame.',
      'Publishing and scheduling — posted at the times your audience is actually awake and free, planned around prayer times and the Friday–Saturday weekend.',
      'Community management — comments and DMs answered in Arabic and English, with a response protocol you approve for pricing questions, complaints, and press.',
      'Seasonal campaign planning — Ramadan, Eid, Saudi National Day, Founding Day, and your own commercial calendar, planned months out instead of scrambled together the week before.',
      'Monthly report — reach, engagement, follower growth, top-performing content, and what we are changing next month.',
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'we map your goals, your audience, and which platforms actually deserve your budget. Some businesses should not be on four platforms. We will tell you that.' },
      { label: 'Monthly plan', text: 'you receive the content calendar for the coming month and approve it before production starts.' },
      { label: 'Production', text: 'content shot, designed, and written. See our content production service for how that runs.' },
      { label: 'Publish and manage', text: 'everything goes out on schedule; comments and messages are handled daily.' },
      { label: 'Report and adjust', text: "you get the numbers at the end of the month, and next month's plan reflects what they told us." },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Restaurants and cafés · Hotels and hospitality · Healthcare and clinics · Retail and e-commerce · Real estate and developers · Automotive · Education · Industrial and manufacturing · Government and semi-government entities',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: 'We are not a social media agency that outsources the filming. We are a film and software company that also runs social media, which means the content on your feed is produced by the same crew that shoots commercial films for global brands — 15+ years, 1,000+ projects, 20+ global brands.\n\nThat matters practically. When you need a video by Thursday, we do not brief a freelancer and hope. We shoot it.',
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'Every piece of content is produced to Saudi advertising standards: modest dress, no wealth flaunting, no children in promotional content, no claims we cannot support. Paid promotions are labelled as advertising. When a campaign calls for creators, we work only through Mawthooq-licensed influencers.\n\nMarketing that grows your brand — and protects it.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'Which platforms should my business be on in Saudi Arabia?', a: 'It depends entirely on who buys from you. A clinic in Riyadh and an industrial supplier in Jubail should not have the same platform mix. We answer this specifically in the strategy session rather than putting you on everything by default.' },
      { q: 'Do you write in Arabic, or translate from English?', a: 'We write in Arabic. Translated Arabic reads as translated Arabic, and Saudi audiences notice immediately. Where your audience is bilingual, we write both versions natively.' },
      { q: 'How often will you post?', a: 'That is set in your monthly plan and depends on your retainer scope and platform mix. We would rather post three strong pieces a week than seven weak ones.' },
      { q: 'Who owns the accounts and the content?', a: 'You do. Always. Accounts stay in your name with your admin access, and every asset we produce is yours. If we ever stop working together, nothing walks out the door with us.' },
      { q: 'Do you handle comments and direct messages?', a: 'Yes, within your agreed scope. We build a response protocol with you covering pricing questions, complaints, and anything that needs to escalate to you before we reply.' },
      { q: 'Can you work alongside our in-house marketing team?', a: 'Yes. Some clients want everything run for them; others want us handling production and strategy while their team publishes. Both work.' },
      { q: 'Do you work with influencers?', a: 'Yes, through Mawthooq-licensed creators only. Unlicensed influencer advertising is a regulatory exposure we will not put a client into.' },
      { q: 'How long before we see results?', a: 'Community growth and engagement usually move within the first two to three months of consistent publishing. Anyone who promises you a specific number by a specific date is guessing.' },
      { q: 'Do you only work in Riyadh?', a: 'We work across the Kingdom — Riyadh, Jeddah, Khobar, Dammam, Jubail, and the Eastern Province — and we travel for production.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'seo-saudi', 'content-production-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'google-ads-saudi',
    titleEn: 'Google Ads Management in Saudi Arabia',
    titleAr: 'إدارة إعلانات Google في المملكة العربية السعودية',
    descEn: 'Google Ads managed for Saudi businesses — Arabic and English campaigns, conversion tracking, and full accountability for every riyal of ad spend.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Google Ads Management in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إدارة إعلانات قوقل في السعودية | بريميرا لايف',
    metaDescEn: 'Google Ads managed for Saudi businesses — Arabic and English campaigns, conversion tracking, and full accountability for every riyal of ad spend.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Google Ads is the only channel where people tell you exactly what they want, in their own words, at the moment they want it. It is also the easiest channel to waste money on. We manage Saudi Google Ads accounts with full accountability for every riyal of spend — what it bought, what it returned, and what we are changing because of it.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: 'Someone searching "أفضل عيادة أسنان في الرياض" is not browsing. They have a problem and a wallet open. Whether they land on you or your competitor is decided by keyword strategy, ad relevance, landing page quality, and bid management — four things that most Saudi accounts get wrong in the same predictable ways.\n\nThe most common: running English-only campaigns in a country that searches in Arabic. The second most common: sending expensive clicks to a slow homepage instead of a page built to convert.',
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Bilingual keyword research — Arabic and English. Arabic search is not a translation of English search. People use dialect, transliteration, and shorthand that no English keyword list will surface.',
      'Campaign build — Search, Performance Max, YouTube, Display, and remarketing, chosen for your business rather than switched on by default.',
      'Ad copy in both languages — written natively, tested continuously.',
      'Conversion tracking that actually works — GA4, conversion actions, call tracking, and WhatsApp click tracking. Saudi buyers convert on WhatsApp far more than on forms, and an account that only counts form fills is lying to you about its own performance.',
      'Landing page strategy — we build the pages too. If your landing page is the bottleneck, we can fix it instead of writing it up in a report.',
      'Negative keyword management — ongoing, because half of Google Ads is deciding what you refuse to pay for.',
      'Budget pacing including VAT — Saudi ad spend carries 15% VAT. We plan for it so your budget means what you think it means.',
      'Monthly reporting — spend, clicks, cost per lead, conversions, and what changed.',
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what a customer is worth to you, what you want to spend, what a good month looks like.' },
      { label: 'Account audit or build', text: 'if you have an account, we audit it and show you what is broken before we touch anything. If you do not, we build it in your name.' },
      { label: 'Launch', text: 'campaigns live with tracking verified before spend starts. Never the other way around.' },
      { label: 'Optimize', text: 'search terms, bids, creative, and landing pages, continuously.' },
      { label: 'Report', text: 'monthly numbers, plainly stated.' },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Healthcare and clinics · Real estate · Legal and professional services · Home services · Automotive · Education · B2B and industrial · E-commerce',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: 'Most Google Ads agencies stop at the click. We are also the company that builds the website the click lands on — 25+ platforms built and running. When the problem is your landing page, and it usually is, we can actually fix it.',
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'Ad copy is written to Saudi advertising standards. No claims we cannot support, no misleading offers, no fabricated urgency. If a claim you want to run cannot be substantiated, we will say so before it goes live rather than after a regulator asks.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'What budget do I need for Google Ads in Saudi Arabia?', a: 'It depends on your industry, your competition, and what a customer is worth to you. Cost per click in Saudi legal or real estate looks nothing like a local service business. We work this out with you in the strategy session, against real numbers rather than a generic figure.' },
      { q: 'Who owns the Google Ads account?', a: 'You do. It is created in your name, you have admin access, and it stays with you. Agencies that keep the account hostage are protecting themselves, not you.' },
      { q: 'Can you take over our existing account?', a: 'Yes. We audit it first and show you what we found before changing anything. Sometimes the existing structure is worth keeping.' },
      { q: 'Do you run ads in Arabic or English?', a: 'Both, where both make sense. Most Saudi accounts should be Arabic-led with English support, but it depends on your customer.' },
      { q: 'Is ad spend included in your fee?', a: 'No. Ad spend goes directly to Google from your account, and our management is separate. You always see exactly what Google was paid.' },
      { q: 'How long before we see results?', a: 'Search campaigns can produce leads in the first week. Getting cost per lead to a good place typically takes two to three months of data and iteration. We do not promise a number.' },
      { q: 'Do you build the landing pages too?', a: 'Yes. That is our Digital Experiences division — custom-coded, fast, and built to convert rather than a template.' },
      { q: 'Do you report on ad spend?', a: 'Every month, fully. Spend, cost per lead, conversions, and what we changed. No vanity metrics.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'seo-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'facebook-instagram-ads-saudi',
    titleEn: 'Facebook & Instagram Ads in Saudi Arabia',
    titleAr: 'إعلانات فيسبوك وإنستغرام في المملكة العربية السعودية',
    descEn: 'Meta ads managed for Saudi businesses — Arabic creative, proper pixel and conversions API setup, and monthly reporting on every riyal spent.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Facebook & Instagram Ads in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إعلانات فيسبوك وإنستغرام في السعودية | بريميرا لايف',
    metaDescEn: 'Meta ads managed for Saudi businesses — Arabic creative, proper pixel and conversions API setup, and monthly reporting on every riyal spent.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'On Google, people search for you. On Instagram, you have to earn the stop. Meta advertising is won or lost on creative — and creative is the one thing most ad agencies quietly outsource. We shoot it ourselves.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: "Meta's targeting is no longer the advantage it was. Since the iOS privacy changes, the platform leans far harder on creative signals than on audience settings. Which means the agency running your account can have perfect campaign structure and still fail, because the video is boring.\n\nThe businesses winning on Instagram in Saudi Arabia are not the ones with the cleverest targeting. They are the ones producing enough good creative, often enough, to keep testing.",
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Meta Business Manager setup — properly configured, in your name, with the right permissions and asset ownership.',
      'Pixel and Conversions API — server-side tracking so you are not flying blind on iOS traffic. This is where most Saudi accounts are quietly broken.',
      'Creative production — video, photography, and design produced in-house by our film crew. Vertical-first, sound-on, built for the feed and for Reels.',
      'Arabic and English creative — captions and on-screen text written natively in both.',
      'Campaign structure — prospecting, retargeting, and lookalikes, structured so you can actually tell what is working.',
      'Click-to-WhatsApp campaigns — Saudi buyers overwhelmingly prefer messaging over forms. We build for how people here actually buy.',
      'Catalogue and shopping setup for e-commerce and retail.',
      'Continuous creative testing — new angles every month, because Meta creative fatigues fast.',
      'Monthly reporting — spend, cost per result, best and worst creative, and what is next.',
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'audience, offer, and what a conversion is worth.' },
      { label: 'Technical setup', text: 'Business Manager, pixel, Conversions API, catalogue. Verified before spend.' },
      { label: 'Creative production', text: 'shot in a planned batch so the account never runs dry.' },
      { label: 'Launch and test', text: 'structured testing, not guessing.' },
      { label: 'Report and iterate', text: "monthly numbers and next month's creative plan." },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Restaurants and F&B · Retail and e-commerce · Beauty and wellness · Hotels and hospitality · Healthcare · Real estate · Education',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: "Ad agencies brief creative. We produce it. Our Cinematic Production division shoots commercial films for global brands, and that is the same crew producing your Meta creative — 20+ global brands, 1,000+ projects.\n\nThe practical difference: when creative fatigues in week three, we can shoot new assets. We are not waiting on a freelancer's availability.",
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'All creative is produced to Saudi advertising standards — modest dress, no wealth flaunting, no children in promotional content. Paid partnerships are disclosed. Creator collaborations run exclusively through Mawthooq-licensed influencers. We do not use the WhatsApp or Meta logos in ways that breach their trademark guidelines.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'Facebook or Instagram — which should we be on?', a: 'Both are bought through the same platform, so it is rarely either/or. The real question is which placements deserve your budget, and that depends on your audience.' },
      { q: 'Who owns the ad account and the pixel?', a: 'You do. Everything is created inside your Business Manager, in your name.' },
      { q: 'Do you produce the video and photos?', a: 'Yes, in-house. That is the core of what we do.' },
      { q: 'What about the iOS tracking changes?', a: 'We implement the Conversions API so conversions are tracked server-side. If your current account only runs the browser pixel, it is under-reporting and over-paying.' },
      { q: 'Can you run click-to-WhatsApp ads?', a: 'Yes. For many Saudi businesses this outperforms form-fill campaigns significantly.' },
      { q: 'Do you work with influencers?', a: 'Only Mawthooq-licensed creators. Non-negotiable.' },
      { q: 'How much creative do you need per month?', a: 'Enough to keep testing without fatiguing. That is set in your plan, and it is the single biggest factor in Meta performance.' },
      { q: 'Do you guarantee a cost per lead?', a: 'No. Anyone who does is either guessing or planning to move the goalposts. We commit to transparent reporting and continuous iteration.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['snapchat-tiktok-ads-saudi', 'content-production-saudi', 'social-media-management-saudi', 'google-ads-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'snapchat-tiktok-ads-saudi',
    titleEn: 'Snapchat & TikTok Ads in Saudi Arabia',
    titleAr: 'إعلانات سناب شات وتيك توك في المملكة العربية السعودية',
    descEn: 'Snapchat and TikTok advertising for Saudi businesses — vertical creative shot in-house, campaign management, and monthly reporting. No repurposed landscape video.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Snapchat & TikTok Ads in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إعلانات سناب وتيك توك في السعودية | بريميرا لايف',
    metaDescEn: 'Snapchat and TikTok advertising for Saudi businesses — vertical creative shot in-house, campaign management, and monthly reporting. No repurposed landscape video.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Snapchat and TikTok are where young Saudi Arabia actually spends its attention. They are also where the most ad money gets wasted, because most brands treat them as a place to dump the landscape video they already made. Vertical video is not a crop. It is a format, and it has to be shot for the format.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: "Snapchat's reach among young Saudi audiences is among the strongest of any market in the world. TikTok has become the default discovery engine for food, retail, and entertainment.\n\nNeither rewards polish for its own sake. They reward creative that looks like it belongs on the platform, hooks in the first two seconds, and works with the sound on. A beautifully graded brand film loses to a well-shot vertical clip every time in this feed.",
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Vertical-native production — shot 9:16 from the start, sound-on, designed for a two-second hook.',
      'Snapchat campaigns — Snap Ads, Story Ads, Collection Ads, and AR lenses or geofilters where they earn their cost.',
      'TikTok campaigns — In-Feed, Spark Ads amplifying creator content, and Video Shopping where relevant.',
      'Arabic creative — on-screen text, voiceover, and captions in Arabic, written natively.',
      'Creator collaborations — through Mawthooq-licensed creators only.',
      'Pixel and event setup — Snap Pixel and TikTok Pixel, verified before launch.',
      'High creative volume — these platforms fatigue faster than any other. Volume is the strategy.',
      "Monthly reporting — spend, cost per result, top creative, next month's plan.",
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'audience, platform fit, and what a result is worth. Not every business belongs on Snapchat.' },
      { label: 'Creative concepting', text: 'hooks and angles built for vertical, not adapted to it.' },
      { label: 'Production', text: 'batch-shot so the account has enough to test.' },
      { label: 'Launch and test', text: 'structured, with tracking verified first.' },
      { label: 'Report and refresh', text: 'new creative every cycle.' },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Restaurants and F&B · Retail and fashion · Beauty · Entertainment and events · Automotive · Education · Consumer apps',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: 'Most agencies running Snapchat in Saudi are media buyers who outsource creative. We are a production company that also buys the media. On these two platforms specifically, that is the whole ballgame — the creative is the campaign.',
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'Modest dress across all casting and imagery. No children in promotional content. No wealth or lifestyle flaunting. Ads labelled as advertising. Creator work exclusively through Mawthooq-licensed influencers — on platforms this creator-heavy, that is where most brands accumulate regulatory risk without realising it.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'Is Snapchat still worth it in Saudi Arabia?', a: 'For consumer brands targeting younger audiences, it remains one of the strongest channels in this market. For B2B and industrial, usually not — and we will tell you that rather than take the budget.' },
      { q: 'Can you use our existing video?', a: 'If it was shot landscape, we would rather not. Cropped landscape video underperforms native vertical badly enough that it is usually cheaper to shoot properly.' },
      { q: 'Do you make AR lenses and filters?', a: 'Yes, where they make sense for the campaign. They are not right for every brand.' },
      { q: 'Do you work with TikTok creators?', a: 'Yes — Mawthooq-licensed only, briefed and managed by us.' },
      { q: 'How fast does creative burn out?', a: 'Faster than any other platform. Plan for a continuous refresh cycle rather than one hero video.' },
      { q: 'Who owns the ad accounts?', a: 'You do, in your name, with your access.' },
      { q: 'Can you handle both platforms together?', a: 'Yes. The creative approach overlaps enough to produce for both in one shoot, which is usually the efficient route.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['facebook-instagram-ads-saudi', 'content-production-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'seo-saudi',
    titleEn: 'SEO in Saudi Arabia',
    titleAr: 'تحسين محركات البحث في المملكة العربية السعودية',
    descEn: 'SEO for Saudi businesses — Arabic and English search, technical fixes, local search, and content built to rank. We build the site too, so fixes actually ship.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'SEO in Saudi Arabia | Arabic & English Search | Premiera Live',
    metaTitleAr: 'تحسين محركات البحث في السعودية | بريميرا لايف',
    metaDescEn: 'SEO for Saudi businesses — Arabic and English search, technical fixes, local search, and content built to rank. We build the site too, so fixes actually ship.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Ads stop the day you stop paying. Search compounds. SEO is the slowest channel we offer and the only one that keeps working after the budget ends — which is exactly why it is worth starting before you need it.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: 'Two things break SEO in Saudi Arabia more than anything else.\n\nThe first is treating Arabic SEO as translated English SEO. Saudis search in Arabic, in dialect, with transliteration and shorthand that no English keyword list contains. The Arabic query and the English query for the same service are often two completely different pieces of content.\n\nThe second is that most agencies can only recommend fixes. They send a technical audit to your web developer, your developer is busy, and eighteen months later the same issues are still there. We build the site, so we ship the fix.',
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Bilingual keyword research — Arabic and English, mapped to real search behaviour rather than translated word lists.',
      'Technical SEO — crawlability, indexation, site speed, Core Web Vitals, correct RTL rendering, and hreflang for ar-SA and en-SA. Bilingual sites break in specific, predictable ways.',
      'On-page optimization — titles, meta descriptions, headings, internal linking, and structured data.',
      'Content clusters — comprehensive coverage of a topic with pages that link to each other, instead of scattered one-off pages competing with themselves.',
      'Local SEO — Google Business Profile for Riyadh, Jeddah, Khobar, Dammam, Jubail, and the Eastern Province, with genuinely distinct content per location rather than duplicated city pages.',
      'Schema markup — organization, service, FAQ, local business, article.',
      'Monthly reporting — rankings, traffic, and the queries actually bringing you business.',
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what you want to be found for, and who you are competing with.' },
      { label: 'Technical audit', text: 'what is broken, in priority order, with the business cost of each.' },
      { label: 'Fix and build', text: 'we implement rather than recommend.' },
      { label: 'Content', text: 'cluster by cluster, in both languages.' },
      { label: 'Report', text: 'monthly, with the honest picture.' },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Healthcare · Real estate · Legal and professional services · Industrial and B2B · Education · Hospitality · E-commerce',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: 'We do not just advise on SEO — we run 25+ platforms of our own. BahrainNights, StudentPhotos, EventsBahrain and others are sites we built, rank, and operate. When we tell you something works, it is because we have done it on our own properties where there was no client to blame.',
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'Content is written to Saudi advertising standards. We do not fabricate reviews, buy spam links, or use tactics that put your domain at risk for a short-term ranking. Everything we do to your site is something we would do to our own.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'How long does SEO take in Saudi Arabia?', a: 'Meaningful movement usually takes three to six months, and competitive terms take longer. Anyone promising page one in 30 days is selling something else.' },
      { q: "Do you guarantee number one rankings?", a: "No. Nobody can, and Google's own guidance says to distrust anyone who does. We commit to the work and transparent reporting." },
      { q: 'Is Arabic SEO different from English SEO?', a: 'Substantially. Different queries, different intent, different competition, and a set of technical issues specific to RTL and bilingual sites.' },
      { q: 'We already have a website — can you work with it?', a: 'Usually yes. If the platform itself is the obstacle — some page builders make real technical SEO impossible — we will tell you plainly rather than bill you for years of workarounds.' },
      { q: 'Do you build the pages you recommend?', a: 'Yes. That is the point.' },
      { q: 'What about backlinks?', a: 'Earned through real content and genuine relationships. We do not buy links. Bought links are a liability with a delayed fuse.' },
      { q: 'Do you do local SEO for multiple cities?', a: 'Yes — with genuinely different content for each city. Thin duplicated city pages get demoted, and they misrepresent your footprint.' },
      { q: 'Can you do SEO while the site is not yet public?', a: 'Yes. Architecture, content, and technical foundations are best built before launch, not retrofitted after.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['google-ads-saudi', 'content-production-saudi', 'social-media-management-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'content-production-saudi',
    titleEn: 'Content Production in Saudi Arabia',
    titleAr: 'إنتاج المحتوى في المملكة العربية السعودية',
    descEn: 'Video, photography, design, and Arabic copy produced in-house for Saudi brands — a month of content from a single planned shoot day.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Content Production in Saudi Arabia | Premiera Live',
    metaTitleAr: 'إنتاج المحتوى في السعودية | بريميرا لايف',
    metaDescEn: 'Video, photography, design, and Arabic copy produced in-house for Saudi brands — a month of content from a single planned shoot day.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Every marketing plan dies in the same place: nobody has the content. The strategy is approved, the calendar is built, the ads are ready — and then someone has to actually shoot something. We are the part of the industry that shoots it.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: 'Most agencies do not produce. They coordinate. The brief goes to a freelancer, the freelancer is busy, the shoot slips two weeks, and the campaign launches with stock footage and a stretched logo.\n\nWe are a film company first — 15+ years, 1,000+ projects, 20+ global brands. Content production is not a service we added to look complete. It is the thing we have always done, applied to the feed.',
    whyAr: 'TODO: copy from Shareef',
    deliverablesEn: [
      'Monthly content shoot days — one planned day producing a month of assets across video, photography, and design.',
      'Vertical-first video — shot 9:16 for Reels, Snapchat, TikTok, and Shorts, with landscape versions where you need them.',
      'Professional photography — product, food, interior, portrait, and event, shot by photographers who do this for global brands.',
      'Motion graphics and design — titles, lower thirds, carousels, and static posts, built to your brand.',
      'Arabic and English copy — written natively in both.',
      'Animation and CGI — where the shot cannot be filmed, our Animation division builds it.',
      'Full asset delivery — every file, every crop, every version, yours to keep.',
    ],
    deliverablesAr: [
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
      'TODO: copy from Shareef',
    ],
    processStepsEn: [
      { label: 'Strategy session', text: 'what content your channels actually need each month, and in what volume.' },
      { label: 'Shot list', text: 'planned against your content calendar and approved by you before the crew moves.' },
      { label: 'Production day', text: 'one efficient day, batch-shot. This is where the cost efficiency comes from.' },
      { label: 'Post-production', text: 'edit, grade, sound, graphics, and versioning for each platform.' },
      { label: 'Delivery', text: 'organized, named, and ready to publish.' },
    ],
    processStepsAr: [
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
      { label: 'TODO: copy from Shareef', text: 'TODO: copy from Shareef' },
    ],
    industriesEn: 'Restaurants and F&B · Hotels and hospitality · Retail and fashion · Healthcare · Real estate · Automotive · Industrial and manufacturing · Events',
    industriesAr: 'TODO: copy from Shareef',
    whyPremieraEn: "Our crew shoots commercial films. The same people, cameras, and lighting that produce a brand film produce your Instagram content. Most social content in this market is shot on a phone by an intern. Yours does not have to be.\n\nWe also handle the whole chain — strategy, production, publishing, and reporting — so nothing gets lost between three vendors blaming each other.",
    whyPremieraAr: 'TODO: copy from Shareef',
    complianceEn: 'Modest dress in all imagery and video. No children in promotional content. No wealth or lifestyle flaunting. Every production is planned to Saudi standards from the shot list stage, not fixed in the edit after somebody notices.',
    complianceAr: 'TODO: copy from Shareef',
    faqsEn: [
      { q: 'How much content comes out of one shoot day?', a: 'That depends on the shot list and the setups, and it is planned in advance. Batch production is what makes a month of content from a single day realistic.' },
      { q: 'Do you shoot outside Riyadh?', a: 'Yes — across the Kingdom, and we travel. Our crew has worked across the GCC for 15+ years.' },
      { q: 'Can you shoot at our location?', a: 'Yes. Restaurants, clinics, factories, hotels, showrooms — location work is standard.' },
      { q: 'Do we own the footage?', a: 'Yes. Everything we shoot for you is yours, including the raw files if you want them.' },
    ],
    faqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
    relatedSlugs: ['social-media-management-saudi', 'facebook-instagram-ads-saudi', 'snapchat-tiktok-ads-saudi', 'google-ads-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
  },
  {
    slug: 'marketing-packages-saudi',
    titleEn: 'Growth Partnership Packages',
    titleAr: 'باقات الشراكة في النمو',
    descEn: 'Three growth partnership tiers — Foundation, Growth, and Scale. Monthly retainers covering strategy, content, advertising, SEO, and reporting.',
    descAr: 'TODO: copy from Shareef',
    metaTitleEn: 'Marketing Packages in Saudi Arabia | Premiera Live',
    metaTitleAr: 'باقات التسويق في السعودية | بريميرا لايف',
    metaDescEn: 'Three growth partnership tiers — Foundation, Growth, and Scale. Monthly retainers covering strategy, content, advertising, SEO, and reporting.',
    metaDescAr: 'TODO: copy from Shareef',
    heroEn: 'Marketing that works is not a campaign you run once. It is a partnership that compounds month after month. We work in three tiers — each one a complete system rather than a list of tasks. Where you start depends on where your business is, and we work that out together on a call.',
    heroAr: 'TODO: copy from Shareef',
    whyEn: '',
    whyAr: '',
    deliverablesEn: [],
    deliverablesAr: [],
    processStepsEn: [],
    processStepsAr: [],
    industriesEn: '',
    industriesAr: '',
    whyPremieraEn: '',
    whyPremieraAr: '',
    complianceEn: '',
    complianceAr: '',
    faqsEn: [],
    faqsAr: [],
    relatedSlugs: ['social-media-management-saudi', 'google-ads-saudi', 'seo-saudi', 'content-production-saudi'],
    ctaEn: 'Call to Discuss',
    ctaAr: 'اتصل بنا للنقاش',
    isPackages: true,
    packagesHeroEn: 'Marketing that works is not a campaign you run once. It is a partnership that compounds month after month. We work in three tiers — each one a complete system rather than a list of tasks. Where you start depends on where your business is, and we work that out together on a call.',
    packagesHeroAr: 'TODO: copy from Shareef',
    packagesTiers: [
      {
        name: 'FOUNDATION',
        taglineEn: 'Establish your digital presence.',
        taglineAr: 'TODO: copy from Shareef',
        builtForEn: 'Startups · Restaurants · Cafés · Clinics · Small businesses · Retail stores',
        builtForAr: 'TODO: copy from Shareef',
        deliverablesEn: [
          { category: 'Strategy', items: ['Initial marketing strategy session', 'Competitor analysis', 'Monthly content calendar', 'Brand direction'] },
          { category: 'Social Media', items: ['Up to 12 posts per month', 'Graphic design', 'Caption writing', 'Hashtag research', 'Content scheduling'] },
          { category: 'Google', items: ['Google Business Profile optimisation', 'Google Search Console monitoring', 'Google Analytics reporting'] },
          { category: 'Monthly Content', items: ['One half-day production session every month, covering:', 'Professional photography', 'Short-form video', 'Reels', 'Product photography'] },
          { category: 'Reporting', items: ['Monthly report: reach, engagement, website traffic, and recommendations'] },
          { category: 'Support', items: ['WhatsApp support during business hours', 'Monthly strategy meeting'] },
        ],
        deliverablesAr: [
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
        ],
        notIncludedEn: 'Google Ads management · Website development · Website maintenance · SEO campaign',
        notIncludedAr: 'TODO: copy from Shareef',
      },
      {
        name: 'GROWTH',
        taglineEn: 'Accelerate leads and sales.',
        taglineAr: 'TODO: copy from Shareef',
        builtForEn: 'SMEs · Manufacturers · Construction · Healthcare · Corporate companies · Hotels',
        builtForAr: 'TODO: copy from Shareef',
        deliverablesEn: [
          { category: 'Everything in Foundation, plus:', items: [] },
          { category: 'Content', items: ['One full production day, covering:', 'Professional photography', 'Commercial video', 'Reels', 'Interviews', 'Behind the scenes', 'Product photography'] },
          { category: 'Performance Marketing', items: ['Google Ads management', 'Keyword research', 'Conversion tracking', 'Monthly optimisation', 'Remarketing', 'Landing page recommendations'] },
          { category: 'Technical SEO', items: ['Website audit', 'Search Console fixes', 'On-page optimisation', 'Performance optimisation', 'Monthly SEO reporting'] },
          { category: 'Analytics', items: ['Custom dashboards', 'Traffic analysis', 'Lead tracking', 'Campaign reporting', 'Return on investment review'] },
          { category: 'Strategy', items: ['Monthly strategy meeting', 'Campaign planning', 'Quarterly roadmap'] },
        ],
        deliverablesAr: [
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
        ],
        notIncludedEn: 'Premium website development · Custom software · CRM integrations. These are quoted separately.',
        notIncludedAr: 'TODO: copy from Shareef',
      },
      {
        name: 'SCALE',
        taglineEn: 'Your dedicated growth partner.',
        taglineAr: 'TODO: copy from Shareef',
        builtForEn: 'Large companies · Enterprise · Government · Luxury brands · Multi-location businesses',
        builtForAr: 'TODO: copy from Shareef',
        deliverablesEn: [
          { category: 'Everything in Growth, plus:', items: [] },
          { category: 'Dedicated Team', items: ['Dedicated account manager', 'Priority support', 'Monthly planning sessions', 'Quarterly business review', 'Marketing roadmap'] },
          { category: 'Production', items: ['Priority booking', 'Multiple production days', 'Commercial campaigns', 'Corporate photography', 'Executive portraits', 'Recruitment videos', 'Product launches'] },
          { category: 'Performance', items: ['Google Ads', 'Meta Ads (Facebook & Instagram)', 'Snapchat Ads', 'TikTok Ads', 'A/B testing', 'Conversion optimisation', 'Advanced reporting'] },
          { category: 'SEO', items: ['Advanced SEO strategy', 'Content planning', 'Technical monitoring', 'Competitor analysis', 'Local SEO'] },
          { category: 'Executive Reporting', items: ['Monthly executive dashboard', 'Campaign performance', 'Lead quality analysis', 'Growth recommendations', 'Quarterly planning presentation'] },
        ],
        deliverablesAr: [
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
          { category: 'TODO: copy from Shareef', items: ['TODO: copy from Shareef'] },
        ],
      },
    ],
    websiteDevEn: 'Website development is quoted separately.',
    websiteDevAr: 'TODO: copy from Shareef',
    websiteDevItemsEn: [
      'Websites are not included in any package. They are built by our Digital Experiences division and quoted per project:',
      'Landing Pages',
      'Business Websites',
      'Premium Corporate Websites',
      'Custom Business Platforms',
      'Scale clients receive:',
      'Priority scheduling',
      'Preferential rates',
      'Direct integration with their marketing strategy',
    ],
    websiteDevItemsAr: ['TODO: copy from Shareef'],
    websiteCareEn: 'Website care can be added to any retainer.',
    websiteCareAr: 'TODO: copy from Shareef',
    websiteCareItemsEn: [
      'After launch, website support can be added to any package:',
      'Hosting management',
      'Security updates',
      'Performance monitoring',
      'Content updates',
      'Technical support',
      'Backups',
      'Uptime monitoring',
      'Minor improvements',
    ],
    websiteCareItemsAr: ['TODO: copy from Shareef'],
    scaleBenefitsEn: [
      'Priority production scheduling',
      'Faster turnaround where feasible',
      'Quarterly website UX reviews',
      'Website maintenance included while under an active Scale retainer',
      'Reduced rates on future website rebuilds or major redesigns',
    ],
    scaleBenefitsAr: ['TODO: copy from Shareef'],
    packagesFaqsEn: [
      { q: 'Which package is right for my business?', a: 'It depends on where you are and what you are trying to do. Foundation suits businesses building a consistent presence for the first time. Growth suits businesses ready to spend on advertising and want leads tracked properly. Scale suits organisations that need a dedicated team. We work it out on the call rather than pushing you up a tier.' },
      { q: 'Can I change packages later?', a: 'Yes. Most clients start at Foundation or Growth and move up as results justify it. Moving down is equally fine.' },
      { q: 'Is advertising spend included?', a: 'No. Ad spend goes directly to Google, Meta, Snapchat, or TikTok from your own accounts. Our management is separate, and you always see exactly what the platforms were paid.' },
      { q: 'Do you require annual contracts?', a: 'We recommend long-term partnerships because marketing results compound and a three-month engagement rarely shows what a channel can do. Every proposal is built around your goals rather than a fixed lock-in.' },
      { q: 'Who owns the accounts, content, and data?', a: 'You do. Accounts stay in your name, every asset we produce is yours, and nothing leaves with us.' },
      { q: 'Can I add website development to a package?', a: 'Yes, quoted separately. Scale clients get priority scheduling and preferential rates on it.' },
      { q: 'What is not included in any package?', a: 'Website development, custom software, and CRM integrations are always quoted separately.' },
      { q: 'Do you work outside Riyadh?', a: 'Yes — across the Kingdom, including Jeddah, Khobar, Dammam, Jubail, and the Eastern Province.' },
    ],
    packagesFaqsAr: [
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
      { q: 'TODO: copy from Shareef', a: 'TODO: copy from Shareef' },
    ],
  },
]

export const MARKETING_SLUGS = SERVICES.map((s) => s.slug)

export function getMarketingService(slug: string): MarketingService | undefined {
  return SERVICES.find((s) => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): MarketingService[] {
  return SERVICES.filter((s) => slugs.includes(s.slug))
}

export function getServiceLabel(slug: string, isArabic: boolean): string {
  const s = getMarketingService(slug)
  if (!s) return slug
  return isArabic ? s.titleAr : s.titleEn
}

export default SERVICES
